// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class CardContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cardContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.CardContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsCardSelected("IsCardSelected"),
		SelectedCardIndex("SelectedCardIndex");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CardContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CardContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cardContextMendixObject)
	{
		if (cardContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cardContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cardContextMendixObject = cardContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.CardContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.CardContext(context, mendixObject);
	}

	public static nativemobile.proxies.CardContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.CardContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsCardSelected
	 */
	public final java.lang.Boolean getIsCardSelected()
	{
		return getIsCardSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCardSelected
	 */
	public final java.lang.Boolean getIsCardSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCardSelected.toString());
	}

	/**
	 * Set value of IsCardSelected
	 * @param iscardselected
	 */
	public final void setIsCardSelected(java.lang.Boolean iscardselected)
	{
		setIsCardSelected(getContext(), iscardselected);
	}

	/**
	 * Set value of IsCardSelected
	 * @param context
	 * @param iscardselected
	 */
	public final void setIsCardSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscardselected)
	{
		getMendixObject().setValue(context, MemberNames.IsCardSelected.toString(), iscardselected);
	}

	/**
	 * @return value of SelectedCardIndex
	 */
	public final java.lang.Integer getSelectedCardIndex()
	{
		return getSelectedCardIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedCardIndex
	 */
	public final java.lang.Integer getSelectedCardIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SelectedCardIndex.toString());
	}

	/**
	 * Set value of SelectedCardIndex
	 * @param selectedcardindex
	 */
	public final void setSelectedCardIndex(java.lang.Integer selectedcardindex)
	{
		setSelectedCardIndex(getContext(), selectedcardindex);
	}

	/**
	 * Set value of SelectedCardIndex
	 * @param context
	 * @param selectedcardindex
	 */
	public final void setSelectedCardIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer selectedcardindex)
	{
		getMendixObject().setValue(context, MemberNames.SelectedCardIndex.toString(), selectedcardindex);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cardContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.CardContext that = (nativemobile.proxies.CardContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
