// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class Card implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cardMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.Card";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CardNumber("CardNumber"),
		CVV("CVV"),
		ExpiryDate("ExpiryDate"),
		NameOnCard("NameOnCard"),
		Card_Cards("NativeMobile.Card_Cards");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Card(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Card(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cardMendixObject)
	{
		if (cardMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cardMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cardMendixObject = cardMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.Card initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.Card(context, mendixObject);
	}

	public static nativemobile.proxies.Card load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.Card.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.Card> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nativemobile.proxies.Card.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of CardNumber
	 */
	public final java.lang.String getCardNumber()
	{
		return getCardNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CardNumber
	 */
	public final java.lang.String getCardNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CardNumber.toString());
	}

	/**
	 * Set value of CardNumber
	 * @param cardnumber
	 */
	public final void setCardNumber(java.lang.String cardnumber)
	{
		setCardNumber(getContext(), cardnumber);
	}

	/**
	 * Set value of CardNumber
	 * @param context
	 * @param cardnumber
	 */
	public final void setCardNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cardnumber)
	{
		getMendixObject().setValue(context, MemberNames.CardNumber.toString(), cardnumber);
	}

	/**
	 * @return value of CVV
	 */
	public final java.lang.String getCVV()
	{
		return getCVV(getContext());
	}

	/**
	 * @param context
	 * @return value of CVV
	 */
	public final java.lang.String getCVV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CVV.toString());
	}

	/**
	 * Set value of CVV
	 * @param cvv
	 */
	public final void setCVV(java.lang.String cvv)
	{
		setCVV(getContext(), cvv);
	}

	/**
	 * Set value of CVV
	 * @param context
	 * @param cvv
	 */
	public final void setCVV(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cvv)
	{
		getMendixObject().setValue(context, MemberNames.CVV.toString(), cvv);
	}

	/**
	 * @return value of ExpiryDate
	 */
	public final java.lang.String getExpiryDate()
	{
		return getExpiryDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpiryDate
	 */
	public final java.lang.String getExpiryDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExpiryDate.toString());
	}

	/**
	 * Set value of ExpiryDate
	 * @param expirydate
	 */
	public final void setExpiryDate(java.lang.String expirydate)
	{
		setExpiryDate(getContext(), expirydate);
	}

	/**
	 * Set value of ExpiryDate
	 * @param context
	 * @param expirydate
	 */
	public final void setExpiryDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expirydate)
	{
		getMendixObject().setValue(context, MemberNames.ExpiryDate.toString(), expirydate);
	}

	/**
	 * @return value of NameOnCard
	 */
	public final java.lang.String getNameOnCard()
	{
		return getNameOnCard(getContext());
	}

	/**
	 * @param context
	 * @return value of NameOnCard
	 */
	public final java.lang.String getNameOnCard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NameOnCard.toString());
	}

	/**
	 * Set value of NameOnCard
	 * @param nameoncard
	 */
	public final void setNameOnCard(java.lang.String nameoncard)
	{
		setNameOnCard(getContext(), nameoncard);
	}

	/**
	 * Set value of NameOnCard
	 * @param context
	 * @param nameoncard
	 */
	public final void setNameOnCard(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nameoncard)
	{
		getMendixObject().setValue(context, MemberNames.NameOnCard.toString(), nameoncard);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Card_Cards
	 */
	public final nativemobile.proxies.Cards getCard_Cards() throws com.mendix.core.CoreException
	{
		return getCard_Cards(getContext());
	}

	/**
	 * @param context
	 * @return value of Card_Cards
	 * @throws com.mendix.core.CoreException
	 */
	public final nativemobile.proxies.Cards getCard_Cards(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nativemobile.proxies.Cards result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Card_Cards.toString());
		if (identifier != null) {
			result = nativemobile.proxies.Cards.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Card_Cards
	 * @param card_cards
	 */
	public final void setCard_Cards(nativemobile.proxies.Cards card_cards)
	{
		setCard_Cards(getContext(), card_cards);
	}

	/**
	 * Set value of Card_Cards
	 * @param context
	 * @param card_cards
	 */
	public final void setCard_Cards(com.mendix.systemwideinterfaces.core.IContext context, nativemobile.proxies.Cards card_cards)
	{
		if (card_cards == null) {
			getMendixObject().setValue(context, MemberNames.Card_Cards.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Card_Cards.toString(), card_cards.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cardMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.Card that = (nativemobile.proxies.Card) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
