define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "?f3c8":
/*!**************************************************************!*\
  !*** @react-native-community/async-storage (ignored module) ***!
  \**************************************************************/
/***/ (() => {

/* empty */

/***/ }),

/***/ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/GetStorageItemObject.js":
/*!*************************************************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/GetStorageItemObject.js ***!
  \*************************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   GetStorageItemObject: () => (/* binding */ GetStorageItemObject)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var _react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @react-native-community/async-storage */ "?f3c8");
/* harmony import */ var _react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_2__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.




// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * What does this JavaScript action do?
 * 
 * Get locally stored JSON object stored in clients internet browser. Identified by a unique key. Can be accessed by the GetStorageItemObject action. Please note that users can clear the device storage.
 * @param {string} key - This field is required.
 * @param {string} entity - This field is required.
 * @returns {Promise.<MxObject>}
 */
async function GetStorageItemObject(key, entity) {
  // BEGIN USER CODE
  if (!key) {
    return Promise.reject(new Error("Input parameter 'Key' is required"));
  }
  if (!entity) {
    return Promise.reject(new Error("Input parameter 'Entity' is required"));
  }
  return getItem(key).then(result => {
    if (result === null) {
      return Promise.reject(new Error(`Storage item '${key}' does not exist`));
    }
    const value = JSON.parse(result);
    return getOrCreateMxObject(entity, value).then(newObject => {
      const newValue = serializeMxObject(newObject);
      return setItem(key, JSON.stringify(newValue)).then(() => newObject);
    });
  });
  function getItem(key) {
    if (navigator && navigator.product === "ReactNative") {
      return _react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_2___default().getItem(key);
    }
    if (window) {
      const value = window.localStorage.getItem(key);
      return Promise.resolve(value);
    }
    return Promise.reject(new Error("No storage API available"));
  }
  function setItem(key, value) {
    if (navigator && navigator.product === "ReactNative") {
      return _react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_2___default().setItem(key, value);
    }
    if (window) {
      window.localStorage.setItem(key, value);
      return Promise.resolve();
    }
    return Promise.reject(new Error("No storage API available"));
  }
  function getOrCreateMxObject(entity, value) {
    return getMxObject(value.guid).then(existingObject => {
      if (existingObject) {
        return existingObject;
      } else {
        return createMxObject(entity, value);
      }
    });
  }
  function getMxObject(guid) {
    return new Promise((resolve, reject) => {
      mx.data.get({
        guid,
        callback: mxObject => resolve(mxObject),
        error: error => reject(error)
      });
    });
  }
  function createMxObject(entity, value) {
    return new Promise((resolve, reject) => {
      mx.data.create({
        entity,
        callback: mxObject => {
          Object.keys(value).filter(attribute => attribute !== "guid").forEach(attributeName => {
            const attributeValue = value[attributeName];
            mxObject.set(attributeName, attributeValue);
          });
          resolve(mxObject);
        },
        error: () => reject(new Error(`Could not create '${entity}' object`))
      });
    });
  }
  function serializeMxObject(object) {
    return object.getAttributes().reduce((accumulator, attributeName) => {
      accumulator[attributeName] = object.get(attributeName);
      return accumulator;
    }, {
      guid: object.getGuid()
    });
  }
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_PopulateFeedbackMetadata.js":
/*!********************************************************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_PopulateFeedbackMetadata.js ***!
  \********************************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_PopulateFeedbackMetadata: () => (/* binding */ JS_PopulateFeedbackMetadata)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
const handleUserRoles = async () => {
  if (!mx) return undefined;
  try {
    return await mx.session.getUserRoleNames();
  } catch (error) {
    console.error("Error getting user role names", error);
    return undefined;
  }
};
const handlePagePath = async () => {
  if (!mx) return undefined;
  try {
    const mendixVersion = mx.version;
    const mendixMajorVersion = mendixVersion.split('.')[0];
    switch (mendixMajorVersion) {
      case '9':
      case '10':
        return mx.ui.getContentForm().path.toString();
      default:
        return undefined;
    }
    ;
  } catch {
    console.error("Error getting page path", error);
    return undefined;
  }
};
// END EXTRA CODE

/**
 * What does this JavaScript action do?
 * 
 * Returns meta data from the clients internet browser. 
 * 
 * This includes; 
 * 
 * ActiveUserRoles
 * PageName
 * EnvironmentURL
 * Browser
 * ScreenWidth
 * ScreenHeight
 * @param {MxObject} feedback
 * @returns {Promise.<MxObject>}
 */
async function JS_PopulateFeedbackMetadata(feedback) {
  // BEGIN USER CODE
  try {
    const userRoles = await handleUserRoles();
    const pagePath = await handlePagePath();
    feedback.set("ActiveUserRoles", userRoles);
    feedback.set("PageName", pagePath);
    feedback.set("EnvironmentURL", window.location.href);
    feedback.set("Browser", navigator.userAgent);
    feedback.set("ScreenWidth", window.screen.width);
    feedback.set("ScreenHeight", window.screen.height);
    return feedback;
  } catch (error) {
    console.error("Error setting meta data", error);
  }
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_RevokeUploadedFileFromMemory.js":
/*!************************************************************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_RevokeUploadedFileFromMemory.js ***!
  \************************************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_RevokeUploadedFileFromMemory: () => (/* binding */ JS_RevokeUploadedFileFromMemory)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * What does this JavaScript action do?
 * 
 * After you have uploaded an image it removes locally stored image from memory. This is a custom build action.
 * 
 * Dependency Note: 
 * This JavaScript action should be used only when you have inserted the Image Upload JavaScript Action called 'JS_UploadAndConvertToFileBlobURL' into your nanoflow.
 * 
 * More detailed explanation:  Memory management.
 * 
 * To upload a image we use a custom build Javascript action called  'JS_UploadAndConvertToFileBlobURL'.
 * Inside this action we use a JavaScript method called createObjectURL() to upload and store files in local memory. We can access and cosume this in memory image resource via the URL path that is returned from the createObjectURL() method. 
 * 
 * However, each time you call createObjectURL(), a new object is created in memory, even if you've already created one for the same object. 
 * So each of these must be released by calling this action called 'JS_RevokeUploadedFileFromMemory' when you no longer need them.
 * 
 * Browsers will release object URLs automatically when the document is unloaded; however, for optimal performance and memory usage, if there are safe times when you can explicitly unload them, you should do so with the JavaScriptAction called 'JS_RevokeUploadedFileFromMemory'.
 * @param {string} fileBlobURL - You have to pass the fileBlobURL that was created using the URL.createObjectURL() in the JS Action called 'JS_UploadAndConvertToFileBlobURL'
 * @returns {Promise.<void>}
 */
async function JS_RevokeUploadedFileFromMemory(fileBlobURL) {
  // BEGIN USER CODE
  /* We use the URL.createObjectURL() static method which creates a string containing a URL representing the
     image uploaded. 
     The image blob is stored in the clients browser and takes up memory whilst the session is active. So here we 
     revoke the image when the user deletes the image. Note that the image is automaticlly revoked when the browser refreshes
     or closes.
  
     You have to pass the fileBlobURL that was created using the URL.createObjectURL() in the JS Action called 'JS_UploadAndConvertToFileBlobURL'
   */
  if (fileBlobURL && typeof fileBlobURL === "string") {
    URL.revokeObjectURL(fileBlobURL);
  } else {
    throw new Error("Image was not removed from browser memory");
  }
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackAnnotateWidget.js":
/*!************************************************************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackAnnotateWidget.js ***!
  \************************************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_ToggleFeedbackAnnotateWidget: () => (/* binding */ JS_ToggleFeedbackAnnotateWidget)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// messageActionTypes are to identify the postMessage types between the JS Action & Feedback Widget.
const messageAction_toggleAnnotateMode = "mxFeedbackWidget_toggleAnnotateMode"; // The Feedback widget reads this to trigger a specific screenshot mode stage.
const messageAction_isBase64 = "mxFeedbackWidget_convertedToBase64"; // We expect this string from the widget when screenshot mode in enabled.
const messageAction_actionCancelled = "mxFeedbackWidget_actionCancelled"; // The Feedback widget will send this back if screenshot/annotation actions are cancelled by the user.

const parseJSON = event => {
  try {
    return JSON.parse(event);
  } catch {
    return undefined;
  }
};
// END EXTRA CODE

/**
 * What does this JavaScript action do?
 * 
 * When you upload a screenshot manually the image can be annotatated. 
 * 
 * More detailed explanation:
 * The Mendix Feedback Widget handles annotation and also renders a default styled button on your page. 
 * 
 * In order to trigger the annotation mode you have to use this JavaScript action to send the widget the correct image payload.
 * 
 * Return Type:
 * Will return base 64 image string
 * @param {string} fileBlobURL
 * @returns {Promise.<string>}
 */
async function JS_ToggleFeedbackAnnotateWidget(fileBlobURL) {
  // BEGIN USER CODE
  /* 
  The widget and JS action communicate with the following postMessage object structure:
  messageObject = {messageActionType: string;messageData: string;}
  */
  const messageObject = {
    "messageActionType": messageAction_toggleAnnotateMode,
    // The widget reads this to trigger the Annotate Mode.
    "messageData": fileBlobURL // The widget uses this URL reference to get access to the locally stored image blob.
  };
  postMessage(JSON.stringify(messageObject), window.origin); // Send the serialized message object to Feedback Wiget to trigger annotate mode.

  return new Promise(resolve => {
    function handleEvent(event) {
      const parsedData = parseJSON(event.data); // Convert the received string to an object.

      if (event.origin === window.origin) {
        if (parsedData && parsedData.messageActionType === messageAction_isBase64) {
          window.removeEventListener("message", handleEvent);
          resolve(parsedData.messageData); // Resolve & return the base64 image to the nanoflow.
        }
        ;
        if (parsedData && parsedData.messageActionType === messageAction_actionCancelled) {
          resolve();
        }
      }
    }
    ;
    window.addEventListener("message", handleEvent); // Listen and wait for the Feedback Widget to send the base64 image.
  });
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackScreenshotWidget.js":
/*!**************************************************************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackScreenshotWidget.js ***!
  \**************************************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_ToggleFeedbackScreenshotWidget: () => (/* binding */ JS_ToggleFeedbackScreenshotWidget)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// messageActionTypes are to identify the postMessage types between the JS Action & Feedback Widget.
const messageAction_toggleAnnotateMode = "mxFeedbackWidget_toggleScreenshotMode"; // The Feedback widget reads this to trigger a specific screenshot mode stage.
const messageAction_isBase64 = "mxFeedbackWidget_convertedToBase64"; // We expect this string from the widget when screenshot mode in enabled.
const messageAction_actionCancelled = "mxFeedbackWidget_actionCancelled"; // The Feedback widget will send this back if screenshot/annotation actions are cancelled by the user.

/* 
	The widget and JS action communicate with the following postMessage object structure:
	messageObject = {messageActionType: string;messageData: string;}
*/
const messageObject = {
  "messageActionType": messageAction_toggleAnnotateMode //The Feedback widget reads this to trigger a specific Mode.
};
const parseJson = event => {
  try {
    return JSON.parse(event);
  } catch {
    return undefined;
  }
};
// END EXTRA CODE

/**
 * What does this JavaScript action do?
 * 
 * Lets to take a screenshot of the current visible page
 * 
 * More detailed explanation:
 * The Mendix Feedback Widget handles annotation, screenshot and also renders a default styled button on your page. 
 * 
 * Usage:
 * You should use this JavaScript action to trigger the screenshot functionality.
 * 
 * Return Type:
 * Will return a image base64 string
 * 
 * @returns {Promise.<string>}
 */
async function JS_ToggleFeedbackScreenshotWidget() {
  // BEGIN USER CODE
  postMessage(JSON.stringify(messageObject), window.origin); // Send a message to the Feedback Wiget to trigger screenshot mode.

  return new Promise(resolve => {
    function handleEvent(event) {
      const parsedData = parseJson(event.data);
      if (parsedData && event.origin === window.origin) {
        if (parsedData.messageActionType === messageAction_isBase64) {
          window.removeEventListener("message", handleEvent);
          resolve(parsedData.messageData); // Resolve & return the base64 image to the nanoflow.
        }
        ;
        if (parsedData.messageActionType === messageAction_actionCancelled) {
          resolve("uploadCancelled");
        }
      }
    }
    ;
    window.addEventListener("message", handleEvent); // Listen and wait for the Feedback Widget to send back the edited screenshot as base64.
  });
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_UploadAndConvertToFileBlobURL.js":
/*!*************************************************************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_UploadAndConvertToFileBlobURL.js ***!
  \*************************************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_UploadAndConvertToFileBlobURL: () => (/* binding */ JS_UploadAndConvertToFileBlobURL)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
var isUploading = false;
async function storeFileAndGetResourceUrl(file) {
  return URL.createObjectURL(file); // Saves the file to locally memory and returns a URL path to the Blob object.
}
;
function removeDomElements(_ref) {
  let {
    fileInput,
    progressId
  } = _ref;
  if (progressId) mx.ui.hideProgress(progressId);
  if (fileInput) document.body.removeChild(fileInput);
  isUploading = false;
}
function validateFileTypes(_ref2) {
  let {
    acceptedTypes,
    fileType
  } = _ref2;
  if (!acceptedTypes && !fileType) return false;
  const accepted = acceptedTypes.split(",");
  return accepted.some(type => new RegExp(type).test(fileType));
}
function validateFileSize(_ref3) {
  let {
    uploadedFile,
    maxSize
  } = _ref3;
  if (!uploadedFile && !maxSize) return false;
  const uploadedSize = uploadedFile.size / 1024 / 1024; // Convert to MB
  return uploadedSize < maxSize.c[0] + 0.1; // 0.1 MB extra tolerance
}
// END EXTRA CODE

/**
 * What does this JavaScript Action do?
 * 
 * This is a custom build JavaScript Action that triggers the file upload dialog box to open in your internet browser. 
 * 
 * Dependency Note: 
 * This JavaScript action should be used with the JavaScript Action called 'JS_RevokeUploadedFileFromMemory' so that the image uploaded is removed from local memory :)
 * 
 * Explanation of this JavaScript Action & Memory management.
 * 
 * We use createObjectURL() to upload and store files in local memory. We can access and cosume this in memory image resource via the URL path that is returned from the createObjectURL() method. 
 * 
 * However, each time you call createObjectURL(), a new object is created in memory, even if you've already created one for the same object. 
 * So each of these must be released by calling the JS Action called 'JS_RevokeUploadedFileFromMemory' when you no longer need them.
 * 
 * Browsers will release object URLs automatically when the document is unloaded; however, for optimal performance and memory usage, if there are safe times when you can explicitly unload them, you should do so with the JavaScriptAction called 'JS_RevokeUploadedFileFromMemory'.
 * @param {string} userDefined_mimeTypes
 * @param {Big} userDefined_fileUploadSize
 * @returns {Promise.<string>}
 */
async function JS_UploadAndConvertToFileBlobURL(userDefined_mimeTypes, userDefined_fileUploadSize) {
  // BEGIN USER CODE
  return new Promise((resolve, reject) => {
    try {
      // Create and append the HTML input element to the body
      const fileInput = document.createElement("input");
      fileInput.style.position = "absolute";
      fileInput.style.left = "-9999px";
      fileInput.name = "fileupload";
      fileInput.id = "fileupload";
      fileInput.type = "file";
      if (userDefined_mimeTypes) {
        fileInput.accept = userDefined_mimeTypes;
      }
      fileInput.multiple = false;
      fileInput.onchange = handleFileUpload;
      document.body.appendChild(fileInput);
      fileInput.addEventListener("cancel", () => resolve("uploadCancelled"));
      fileInput.click();

      // A function used to validate & store the uploaded file to local memory.
      function handleFileUpload(event) {
        isUploading = true;
        const newFile = event.target.files[0];
        const progressId = mx.ui.showProgress(null, true);

        // Check if the uploaded file type matches the user defined accepted types.
        if (!validateFileTypes({
          acceptedTypes: fileInput.accept,
          fileType: newFile.type
        })) {
          removeDomElements({
            fileInput,
            progressId
          });
          resolve("fileTypeNotAccepted");
          return;
        }
        // Check if the uploaded file matches the user defined upload size.
        if (!validateFileSize({
          uploadedFile: newFile,
          maxSize: userDefined_fileUploadSize
        })) {
          removeDomElements({
            fileInput,
            progressId
          });
          resolve("fileSizeNotAccepted");
          return;
        }
        // Store file locally on users device and return path to resource.
        storeFileAndGetResourceUrl(newFile).then(fileBlobURL => {
          if (fileBlobURL && typeof fileBlobURL === "string") {
            removeDomElements({
              fileInput,
              progressId
            });
            resolve(fileBlobURL);
          } else {
            removeDomElements({
              fileInput,
              progressId
            });
            resolve("fileNotConverted");
          }
        });
        return;
      }
      ;
    } catch (error) {
      reject(error);
    }
  });
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/SetStorageItemObject.js":
/*!*************************************************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/SetStorageItemObject.js ***!
  \*************************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   SetStorageItemObject: () => (/* binding */ SetStorageItemObject)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var _react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @react-native-community/async-storage */ "?f3c8");
/* harmony import */ var _react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Store a Mendix object in device storage, identified by a unique key. Can be accesed by the GetStargeItemObject action. Please note that users can clear the device storage.
 * @param {string} key - This field is required.
 * @param {MxObject} value - This field is required.
 * @returns {Promise.<void>}
 */
async function SetStorageItemObject(key, value) {
  // BEGIN USER CODE
  if (!key) {
    return Promise.reject(new Error("Input parameter 'Key' is required"));
  }
  if (!value) {
    return Promise.reject(new Error("Input parameter 'Value' is required"));
  }
  const serializedObject = serializeMxObject(value);
  return setItem(key, JSON.stringify(serializedObject));
  function setItem(key, value) {
    if (navigator && navigator.product === "ReactNative") {
      return _react_native_community_async_storage__WEBPACK_IMPORTED_MODULE_1___default().setItem(key, value);
    }
    if (window) {
      window.localStorage.setItem(key, value);
      return Promise.resolve();
    }
    return Promise.reject(new Error("No storage API available"));
  }
  function serializeMxObject(object) {
    return object.getAttributes().reduce((accumulator, attributeName) => {
      accumulator[attributeName] = object.get(attributeName);
      return accumulator;
    }, {
      guid: object.getGuid()
    });
  }
  // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

"use strict";
module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ }),

/***/ "?391f":
/*!**********************************!*\
  !*** mx-global (ignored module) ***!
  \**********************************/
/***/ (() => {

/* empty */

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry needs to be wrapped in an IIFE because it needs to be in strict mode.
(() => {
"use strict";
/*!*************************************************************************************************************!*\
  !*** ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/deployment/tmp/jsactions.js ***!
  \*************************************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   FeedbackModule$GetStorageItemObject: () => (/* binding */ FeedbackModule$GetStorageItemObject),
/* harmony export */   FeedbackModule$JS_PopulateFeedbackMetadata: () => (/* binding */ FeedbackModule$JS_PopulateFeedbackMetadata),
/* harmony export */   FeedbackModule$JS_RevokeUploadedFileFromMemory: () => (/* binding */ FeedbackModule$JS_RevokeUploadedFileFromMemory),
/* harmony export */   FeedbackModule$JS_ToggleFeedbackAnnotateWidget: () => (/* binding */ FeedbackModule$JS_ToggleFeedbackAnnotateWidget),
/* harmony export */   FeedbackModule$JS_ToggleFeedbackScreenshotWidget: () => (/* binding */ FeedbackModule$JS_ToggleFeedbackScreenshotWidget),
/* harmony export */   FeedbackModule$JS_UploadAndConvertToFileBlobURL: () => (/* binding */ FeedbackModule$JS_UploadAndConvertToFileBlobURL),
/* harmony export */   FeedbackModule$SetStorageItemObject: () => (/* binding */ FeedbackModule$SetStorageItemObject)
/* harmony export */ });
const FeedbackModule$JS_PopulateFeedbackMetadata = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_PopulateFeedbackMetadata */ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_PopulateFeedbackMetadata.js"))).JS_PopulateFeedbackMetadata;
const FeedbackModule$SetStorageItemObject = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/SetStorageItemObject */ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/SetStorageItemObject.js"))).SetStorageItemObject;
const FeedbackModule$JS_ToggleFeedbackScreenshotWidget = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackScreenshotWidget */ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackScreenshotWidget.js"))).JS_ToggleFeedbackScreenshotWidget;
const FeedbackModule$JS_UploadAndConvertToFileBlobURL = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_UploadAndConvertToFileBlobURL */ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_UploadAndConvertToFileBlobURL.js"))).JS_UploadAndConvertToFileBlobURL;
const FeedbackModule$JS_ToggleFeedbackAnnotateWidget = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackAnnotateWidget */ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_ToggleFeedbackAnnotateWidget.js"))).JS_ToggleFeedbackAnnotateWidget;
const FeedbackModule$JS_RevokeUploadedFileFromMemory = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_RevokeUploadedFileFromMemory */ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/JS_RevokeUploadedFileFromMemory.js"))).JS_RevokeUploadedFileFromMemory;
const FeedbackModule$GetStorageItemObject = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/GetStorageItemObject */ "../../../../../../Users/zf_karaymeh/Projects/nativeCardWallet/testProject/javascriptsource/feedbackmodule/actions/GetStorageItemObject.js"))).GetStorageItemObject;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7OztBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNtQjtBQUNVO0FBQ29DOztBQUVqRTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlRSxvQkFBb0JBLENBQUNDLEdBQUcsRUFBRUMsTUFBTSxFQUFFO0VBQ3ZEO0VBQ0csSUFBSSxDQUFDRCxHQUFHLEVBQUU7SUFDTixPQUFPRSxPQUFPLENBQUNDLE1BQU0sQ0FBQyxJQUFJQyxLQUFLLENBQUMsbUNBQW1DLENBQUMsQ0FBQztFQUN6RTtFQUNBLElBQUksQ0FBQ0gsTUFBTSxFQUFFO0lBQ1QsT0FBT0MsT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLHNDQUFzQyxDQUFDLENBQUM7RUFDNUU7RUFDQSxPQUFPQyxPQUFPLENBQUNMLEdBQUcsQ0FBQyxDQUFDTSxJQUFJLENBQUNDLE1BQU0sSUFBSTtJQUMvQixJQUFJQSxNQUFNLEtBQUssSUFBSSxFQUFFO01BQ2pCLE9BQU9MLE9BQU8sQ0FBQ0MsTUFBTSxDQUFDLElBQUlDLEtBQUssQ0FBQyxpQkFBaUJKLEdBQUcsa0JBQWtCLENBQUMsQ0FBQztJQUM1RTtJQUNBLE1BQU1RLEtBQUssR0FBR0MsSUFBSSxDQUFDQyxLQUFLLENBQUNILE1BQU0sQ0FBQztJQUNoQyxPQUFPSSxtQkFBbUIsQ0FBQ1YsTUFBTSxFQUFFTyxLQUFLLENBQUMsQ0FBQ0YsSUFBSSxDQUFDTSxTQUFTLElBQUk7TUFDeEQsTUFBTUMsUUFBUSxHQUFHQyxpQkFBaUIsQ0FBQ0YsU0FBUyxDQUFDO01BQzdDLE9BQU9HLE9BQU8sQ0FBQ2YsR0FBRyxFQUFFUyxJQUFJLENBQUNPLFNBQVMsQ0FBQ0gsUUFBUSxDQUFDLENBQUMsQ0FBQ1AsSUFBSSxDQUFDLE1BQU1NLFNBQVMsQ0FBQztJQUN2RSxDQUFDLENBQUM7RUFDTixDQUFDLENBQUM7RUFDRixTQUFTUCxPQUFPQSxDQUFDTCxHQUFHLEVBQUU7SUFDbEIsSUFBSWlCLFNBQVMsSUFBSUEsU0FBUyxDQUFDQyxPQUFPLEtBQUssYUFBYSxFQUFFO01BQ2xELE9BQU9wQixvRkFBb0IsQ0FBQ0UsR0FBRyxDQUFDO0lBQ3BDO0lBQ0EsSUFBSW1CLE1BQU0sRUFBRTtNQUNSLE1BQU1YLEtBQUssR0FBR1csTUFBTSxDQUFDQyxZQUFZLENBQUNmLE9BQU8sQ0FBQ0wsR0FBRyxDQUFDO01BQzlDLE9BQU9FLE9BQU8sQ0FBQ21CLE9BQU8sQ0FBQ2IsS0FBSyxDQUFDO0lBQ2pDO0lBQ0EsT0FBT04sT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLDBCQUEwQixDQUFDLENBQUM7RUFDaEU7RUFDQSxTQUFTVyxPQUFPQSxDQUFDZixHQUFHLEVBQUVRLEtBQUssRUFBRTtJQUN6QixJQUFJUyxTQUFTLElBQUlBLFNBQVMsQ0FBQ0MsT0FBTyxLQUFLLGFBQWEsRUFBRTtNQUNsRCxPQUFPcEIsb0ZBQW9CLENBQUNFLEdBQUcsRUFBRVEsS0FBSyxDQUFDO0lBQzNDO0lBQ0EsSUFBSVcsTUFBTSxFQUFFO01BQ1JBLE1BQU0sQ0FBQ0MsWUFBWSxDQUFDTCxPQUFPLENBQUNmLEdBQUcsRUFBRVEsS0FBSyxDQUFDO01BQ3ZDLE9BQU9OLE9BQU8sQ0FBQ21CLE9BQU8sQ0FBQyxDQUFDO0lBQzVCO0lBQ0EsT0FBT25CLE9BQU8sQ0FBQ0MsTUFBTSxDQUFDLElBQUlDLEtBQUssQ0FBQywwQkFBMEIsQ0FBQyxDQUFDO0VBQ2hFO0VBQ0EsU0FBU08sbUJBQW1CQSxDQUFDVixNQUFNLEVBQUVPLEtBQUssRUFBRTtJQUN4QyxPQUFPYyxXQUFXLENBQUNkLEtBQUssQ0FBQ2UsSUFBSSxDQUFDLENBQUNqQixJQUFJLENBQUNrQixjQUFjLElBQUk7TUFDbEQsSUFBSUEsY0FBYyxFQUFFO1FBQ2hCLE9BQU9BLGNBQWM7TUFDekIsQ0FBQyxNQUNJO1FBQ0QsT0FBT0MsY0FBYyxDQUFDeEIsTUFBTSxFQUFFTyxLQUFLLENBQUM7TUFDeEM7SUFDSixDQUFDLENBQUM7RUFDTjtFQUNBLFNBQVNjLFdBQVdBLENBQUNDLElBQUksRUFBRTtJQUN2QixPQUFPLElBQUlyQixPQUFPLENBQUMsQ0FBQ21CLE9BQU8sRUFBRWxCLE1BQU0sS0FBSztNQUNwQ3VCLEVBQUUsQ0FBQ0MsSUFBSSxDQUFDQyxHQUFHLENBQUM7UUFDUkwsSUFBSTtRQUNKTSxRQUFRLEVBQUVDLFFBQVEsSUFBSVQsT0FBTyxDQUFDUyxRQUFRLENBQUM7UUFDdkNDLEtBQUssRUFBRUEsS0FBSyxJQUFJNUIsTUFBTSxDQUFDNEIsS0FBSztNQUNoQyxDQUFDLENBQUM7SUFDTixDQUFDLENBQUM7RUFDTjtFQUNBLFNBQVNOLGNBQWNBLENBQUN4QixNQUFNLEVBQUVPLEtBQUssRUFBRTtJQUNuQyxPQUFPLElBQUlOLE9BQU8sQ0FBQyxDQUFDbUIsT0FBTyxFQUFFbEIsTUFBTSxLQUFLO01BQ3BDdUIsRUFBRSxDQUFDQyxJQUFJLENBQUNLLE1BQU0sQ0FBQztRQUNYL0IsTUFBTTtRQUNONEIsUUFBUSxFQUFFQyxRQUFRLElBQUk7VUFDbEJHLE1BQU0sQ0FBQ0MsSUFBSSxDQUFDMUIsS0FBSyxDQUFDLENBQ2IyQixNQUFNLENBQUNDLFNBQVMsSUFBSUEsU0FBUyxLQUFLLE1BQU0sQ0FBQyxDQUN6Q0MsT0FBTyxDQUFDQyxhQUFhLElBQUk7WUFDMUIsTUFBTUMsY0FBYyxHQUFHL0IsS0FBSyxDQUFDOEIsYUFBYSxDQUFDO1lBQzNDUixRQUFRLENBQUNVLEdBQUcsQ0FBQ0YsYUFBYSxFQUFFQyxjQUFjLENBQUM7VUFDL0MsQ0FBQyxDQUFDO1VBQ0ZsQixPQUFPLENBQUNTLFFBQVEsQ0FBQztRQUNyQixDQUFDO1FBQ0RDLEtBQUssRUFBRUEsQ0FBQSxLQUFNNUIsTUFBTSxDQUFDLElBQUlDLEtBQUssQ0FBQyxxQkFBcUJILE1BQU0sVUFBVSxDQUFDO01BQ3hFLENBQUMsQ0FBQztJQUNOLENBQUMsQ0FBQztFQUNOO0VBQ0EsU0FBU2EsaUJBQWlCQSxDQUFDMkIsTUFBTSxFQUFFO0lBQy9CLE9BQU9BLE1BQU0sQ0FBQ0MsYUFBYSxDQUFDLENBQUMsQ0FBQ0MsTUFBTSxDQUFDLENBQUNDLFdBQVcsRUFBRU4sYUFBYSxLQUFLO01BQ2pFTSxXQUFXLENBQUNOLGFBQWEsQ0FBQyxHQUFHRyxNQUFNLENBQUNiLEdBQUcsQ0FBQ1UsYUFBYSxDQUFDO01BQ3RELE9BQU9NLFdBQVc7SUFDdEIsQ0FBQyxFQUFFO01BQUVyQixJQUFJLEVBQUVrQixNQUFNLENBQUNJLE9BQU8sQ0FBQztJQUFFLENBQUMsQ0FBQztFQUNsQztFQUNIO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUN2R0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDbUI7QUFDVTs7QUFFN0I7QUFDSSxNQUFNQyxlQUFlLEdBQUcsTUFBQUEsQ0FBQSxLQUFZO0VBQ2hDLElBQUcsQ0FBQ3BCLEVBQUUsRUFBRSxPQUFPcUIsU0FBUztFQUN4QixJQUFJO0lBQ0EsT0FBTyxNQUFNckIsRUFBRSxDQUFDc0IsT0FBTyxDQUFDQyxnQkFBZ0IsQ0FBQyxDQUFDO0VBQzlDLENBQUMsQ0FBQyxPQUFPbEIsS0FBSyxFQUFDO0lBQ1htQixPQUFPLENBQUNuQixLQUFLLENBQUMsK0JBQStCLEVBQUVBLEtBQUssQ0FBQztJQUNyRCxPQUFPZ0IsU0FBUztFQUNwQjtBQUNKLENBQUM7QUFDRCxNQUFNSSxjQUFjLEdBQUcsTUFBQUEsQ0FBQSxLQUFZO0VBQzNCLElBQUcsQ0FBQ3pCLEVBQUUsRUFBRSxPQUFPcUIsU0FBUztFQUN4QixJQUFJO0lBQ0EsTUFBTUssYUFBYSxHQUFHMUIsRUFBRSxDQUFDMkIsT0FBTztJQUNoQyxNQUFNQyxrQkFBa0IsR0FBR0YsYUFBYSxDQUFDRyxLQUFLLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FBQyxDQUFDO0lBQ3RELFFBQU9ELGtCQUFrQjtNQUNyQixLQUFLLEdBQUc7TUFDUixLQUFLLElBQUk7UUFDTCxPQUFPNUIsRUFBRSxDQUFDOEIsRUFBRSxDQUFDQyxjQUFjLENBQUMsQ0FBQyxDQUFDQyxJQUFJLENBQUNDLFFBQVEsQ0FBQyxDQUFDO01BQ2pEO1FBQ0ksT0FBT1osU0FBUztJQUN4QjtJQUFDO0VBQ0wsQ0FBQyxDQUFDLE1BQU07SUFDSkcsT0FBTyxDQUFDbkIsS0FBSyxDQUFDLHlCQUF5QixFQUFFQSxLQUFLLENBQUM7SUFDL0MsT0FBT2dCLFNBQVM7RUFDcEI7QUFDUixDQUFDO0FBQ0w7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlYSwyQkFBMkJBLENBQUNDLFFBQVEsRUFBRTtFQUMzRDtFQUNHLElBQUk7SUFDQSxNQUFNQyxTQUFTLEdBQUcsTUFBTWhCLGVBQWUsQ0FBQyxDQUFDO0lBQ3pDLE1BQU1pQixRQUFRLEdBQUcsTUFBTVosY0FBYyxDQUFDLENBQUM7SUFDdkNVLFFBQVEsQ0FBQ3JCLEdBQUcsQ0FBQyxpQkFBaUIsRUFBRXNCLFNBQVMsQ0FBQztJQUMxQ0QsUUFBUSxDQUFDckIsR0FBRyxDQUFDLFVBQVUsRUFBRXVCLFFBQVEsQ0FBQztJQUNsQ0YsUUFBUSxDQUFDckIsR0FBRyxDQUFDLGdCQUFnQixFQUFFckIsTUFBTSxDQUFDNkMsUUFBUSxDQUFDQyxJQUFJLENBQUM7SUFDcERKLFFBQVEsQ0FBQ3JCLEdBQUcsQ0FBQyxTQUFTLEVBQUV2QixTQUFTLENBQUNpRCxTQUFTLENBQUM7SUFDNUNMLFFBQVEsQ0FBQ3JCLEdBQUcsQ0FBQyxhQUFhLEVBQUVyQixNQUFNLENBQUNnRCxNQUFNLENBQUNDLEtBQUssQ0FBQztJQUNoRFAsUUFBUSxDQUFDckIsR0FBRyxDQUFDLGNBQWMsRUFBRXJCLE1BQU0sQ0FBQ2dELE1BQU0sQ0FBQ0UsTUFBTSxDQUFDO0lBQ2xELE9BQU9SLFFBQVE7RUFDbkIsQ0FBQyxDQUFDLE9BQU85QixLQUFLLEVBQUU7SUFDWm1CLE9BQU8sQ0FBQ25CLEtBQUssQ0FBQyx5QkFBeUIsRUFBRUEsS0FBSyxDQUFDO0VBQ25EO0VBQ0g7QUFDRDs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ3ZFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNtQjtBQUNVOztBQUU3QjtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFldUMsK0JBQStCQSxDQUFDQyxXQUFXLEVBQUU7RUFDbEU7RUFDQTtBQUNEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0VBQ0MsSUFBR0EsV0FBVyxJQUFJLE9BQU9BLFdBQVcsS0FBSyxRQUFRLEVBQUM7SUFDakRDLEdBQUcsQ0FBQ0MsZUFBZSxDQUFDRixXQUFXLENBQUM7RUFDakMsQ0FBQyxNQUFNO0lBQ04sTUFBTSxJQUFJbkUsS0FBSyxDQUFDLDJDQUEyQyxDQUFDO0VBQzdEO0VBQ0E7QUFDRDs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ2pEQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNtQjtBQUNVOztBQUU3QjtBQUNBO0FBQ0EsTUFBTXNFLGdDQUFnQyxHQUFHLHFDQUFxQyxDQUFDLENBQUM7QUFDaEYsTUFBTUMsc0JBQXNCLEdBQUcsb0NBQW9DLENBQUMsQ0FBQztBQUNyRSxNQUFNQyw2QkFBNkIsR0FBRyxrQ0FBa0MsRUFBQzs7QUFFekUsTUFBTUMsU0FBUyxHQUFJQyxLQUFLLElBQUs7RUFDNUIsSUFBSTtJQUNILE9BQU9yRSxJQUFJLENBQUNDLEtBQUssQ0FBQ29FLEtBQUssQ0FBQztFQUN6QixDQUFDLENBQUMsTUFBTTtJQUNQLE9BQU8vQixTQUFTO0VBQ2pCO0FBQ0QsQ0FBQztBQUNEOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNPLGVBQWVnQywrQkFBK0JBLENBQUNSLFdBQVcsRUFBRTtFQUNsRTtFQUNBO0FBQ0Q7QUFDQTtBQUNBO0VBQ0MsTUFBTVMsYUFBYSxHQUFHO0lBQ3JCLG1CQUFtQixFQUFFTixnQ0FBZ0M7SUFBRTtJQUN2RCxhQUFhLEVBQUVILFdBQVcsQ0FBQztFQUM1QixDQUFDO0VBRURVLFdBQVcsQ0FBQ3hFLElBQUksQ0FBQ08sU0FBUyxDQUFDZ0UsYUFBYSxDQUFDLEVBQUU3RCxNQUFNLENBQUMrRCxNQUFNLENBQUMsQ0FBQyxDQUFDOztFQUUzRCxPQUFPLElBQUloRixPQUFPLENBQUNtQixPQUFPLElBQUk7SUFDN0IsU0FBUzhELFdBQVdBLENBQUNMLEtBQUssRUFBRTtNQUMzQixNQUFNTSxVQUFVLEdBQUdQLFNBQVMsQ0FBQ0MsS0FBSyxDQUFDbkQsSUFBSSxDQUFDLENBQUMsQ0FBQzs7TUFFMUMsSUFBR21ELEtBQUssQ0FBQ0ksTUFBTSxLQUFLL0QsTUFBTSxDQUFDK0QsTUFBTSxFQUFFO1FBQ2xDLElBQUlFLFVBQVUsSUFBSUEsVUFBVSxDQUFDQyxpQkFBaUIsS0FBS1Ysc0JBQXNCLEVBQUU7VUFDMUV4RCxNQUFNLENBQUNtRSxtQkFBbUIsQ0FBQyxTQUFTLEVBQUVILFdBQVcsQ0FBQztVQUNsRDlELE9BQU8sQ0FBQytELFVBQVUsQ0FBQ0csV0FBVyxDQUFDLENBQUMsQ0FBQztRQUNsQztRQUFDO1FBQ0QsSUFBR0gsVUFBVSxJQUFJQSxVQUFVLENBQUNDLGlCQUFpQixLQUFLVCw2QkFBNkIsRUFBRTtVQUNoRnZELE9BQU8sQ0FBQyxDQUFDO1FBQ1Y7TUFDRDtJQUVEO0lBQUM7SUFFS0YsTUFBTSxDQUFDcUUsZ0JBQWdCLENBQUMsU0FBUyxFQUFFTCxXQUFXLENBQUMsQ0FBQyxDQUFDO0VBRXJELENBQUMsQ0FBQztFQUNMO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUN6RUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDbUI7QUFDVTs7QUFFN0I7QUFDQTtBQUNBLE1BQU1ULGdDQUFnQyxHQUFHLHVDQUF1QyxDQUFDLENBQUM7QUFDbEYsTUFBTUMsc0JBQXNCLEdBQUcsb0NBQW9DLENBQUMsQ0FBQztBQUNyRSxNQUFNQyw2QkFBNkIsR0FBRyxrQ0FBa0MsRUFBQzs7QUFFekU7QUFDQTtBQUNBO0FBQ0E7QUFDQSxNQUFNSSxhQUFhLEdBQUc7RUFDckIsbUJBQW1CLEVBQUVOLGdDQUFnQyxDQUFDO0FBQ3ZELENBQUM7QUFFRCxNQUFNZSxTQUFTLEdBQUlYLEtBQUssSUFBSztFQUM1QixJQUFJO0lBQ0gsT0FBT3JFLElBQUksQ0FBQ0MsS0FBSyxDQUFDb0UsS0FBSyxDQUFDO0VBQ3pCLENBQUMsQ0FBQyxNQUFNO0lBQ1AsT0FBTy9CLFNBQVM7RUFDakI7QUFDRCxDQUFDO0FBQ0Q7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlMkMsaUNBQWlDQSxDQUFBLEVBQUc7RUFDekQ7RUFDSVQsV0FBVyxDQUFDeEUsSUFBSSxDQUFDTyxTQUFTLENBQUNnRSxhQUFhLENBQUMsRUFBRTdELE1BQU0sQ0FBQytELE1BQU0sQ0FBQyxDQUFDLENBQUM7O0VBRTlELE9BQU8sSUFBSWhGLE9BQU8sQ0FBQ21CLE9BQU8sSUFBSTtJQUU3QixTQUFTOEQsV0FBV0EsQ0FBQ0wsS0FBSyxFQUFDO01BQzFCLE1BQU1NLFVBQVUsR0FBR0ssU0FBUyxDQUFDWCxLQUFLLENBQUNuRCxJQUFJLENBQUM7TUFDeEMsSUFBR3lELFVBQVUsSUFBSU4sS0FBSyxDQUFDSSxNQUFNLEtBQUsvRCxNQUFNLENBQUMrRCxNQUFNLEVBQUU7UUFDaEQsSUFBSUUsVUFBVSxDQUFDQyxpQkFBaUIsS0FBS1Ysc0JBQXNCLEVBQUU7VUFDNUR4RCxNQUFNLENBQUNtRSxtQkFBbUIsQ0FBQyxTQUFTLEVBQUVILFdBQVcsQ0FBQztVQUNsRDlELE9BQU8sQ0FBQytELFVBQVUsQ0FBQ0csV0FBVyxDQUFDLENBQUMsQ0FBQztRQUNsQztRQUFDO1FBQ0QsSUFBR0gsVUFBVSxDQUFDQyxpQkFBaUIsS0FBS1QsNkJBQTZCLEVBQUM7VUFDakV2RCxPQUFPLENBQUMsaUJBQWlCLENBQUM7UUFDM0I7TUFDRDtJQUNEO0lBQUM7SUFFREYsTUFBTSxDQUFDcUUsZ0JBQWdCLENBQUMsU0FBUyxFQUFFTCxXQUFXLENBQUMsQ0FBQyxDQUFDO0VBRWhELENBQUMsQ0FBQztFQUNMO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUN4RUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDNkI7QUFDVjs7QUFFbkI7QUFDSSxJQUFJUSxXQUFXLEdBQUcsS0FBSztBQUV2QixlQUFlQywwQkFBMEJBLENBQUNDLElBQUksRUFBRTtFQUM1QyxPQUFPckIsR0FBRyxDQUFDc0IsZUFBZSxDQUFDRCxJQUFJLENBQUMsQ0FBQyxDQUFDO0FBQ3RDO0FBQUM7QUFFRCxTQUFTRSxpQkFBaUJBLENBQUFDLElBQUEsRUFBMEI7RUFBQSxJQUF6QjtJQUFDQyxTQUFTO0lBQUVDO0VBQVUsQ0FBQyxHQUFBRixJQUFBO0VBQzlDLElBQUdFLFVBQVUsRUFBRXhFLEVBQUUsQ0FBQzhCLEVBQUUsQ0FBQzJDLFlBQVksQ0FBQ0QsVUFBVSxDQUFDO0VBQzdDLElBQUdELFNBQVMsRUFBRUcsUUFBUSxDQUFDQyxJQUFJLENBQUNDLFdBQVcsQ0FBQ0wsU0FBUyxDQUFDO0VBQ2xETixXQUFXLEdBQUcsS0FBSztBQUN2QjtBQUVBLFNBQVNZLGlCQUFpQkEsQ0FBQUMsS0FBQSxFQUE2QjtFQUFBLElBQTNCO0lBQUNDLGFBQWE7SUFBRUM7RUFBUSxDQUFDLEdBQUFGLEtBQUE7RUFDakQsSUFBRyxDQUFDQyxhQUFhLElBQUksQ0FBQ0MsUUFBUSxFQUFFLE9BQU8sS0FBSztFQUM1QyxNQUFNQyxRQUFRLEdBQUdGLGFBQWEsQ0FBQ2xELEtBQUssQ0FBQyxHQUFHLENBQUM7RUFDekMsT0FBT29ELFFBQVEsQ0FBQ0MsSUFBSSxDQUFDQyxJQUFJLElBQUksSUFBSUMsTUFBTSxDQUFDRCxJQUFJLENBQUMsQ0FBQ0UsSUFBSSxDQUFDTCxRQUFRLENBQUMsQ0FBQztBQUNqRTtBQUVBLFNBQVNNLGdCQUFnQkEsQ0FBQUMsS0FBQSxFQUEyQjtFQUFBLElBQXpCO0lBQUNDLFlBQVk7SUFBRUM7RUFBTyxDQUFDLEdBQUFGLEtBQUE7RUFDOUMsSUFBRyxDQUFDQyxZQUFZLElBQUksQ0FBQ0MsT0FBTyxFQUFFLE9BQU8sS0FBSztFQUMxQyxNQUFNQyxZQUFZLEdBQUdGLFlBQVksQ0FBQ0csSUFBSSxHQUFHLElBQUksR0FBRyxJQUFJLENBQUMsQ0FBQztFQUN0RCxPQUFPRCxZQUFZLEdBQUlELE9BQU8sQ0FBQ0csQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLEdBQUksQ0FBQyxDQUFDO0FBQ2hEO0FBQ0o7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNPLGVBQWVDLGdDQUFnQ0EsQ0FBQ0MscUJBQXFCLEVBQUVDLDBCQUEwQixFQUFFO0VBQ3pHO0VBQ0csT0FBTyxJQUFJdkgsT0FBTyxDQUFDLENBQUNtQixPQUFPLEVBQUVsQixNQUFNLEtBQUs7SUFDcEMsSUFBSTtNQUNBO01BQ0EsTUFBTThGLFNBQVMsR0FBR0csUUFBUSxDQUFDc0IsYUFBYSxDQUFDLE9BQU8sQ0FBQztNQUNqRHpCLFNBQVMsQ0FBQzBCLEtBQUssQ0FBQ0MsUUFBUSxHQUFHLFVBQVU7TUFDckMzQixTQUFTLENBQUMwQixLQUFLLENBQUNFLElBQUksR0FBRyxTQUFTO01BQ2hDNUIsU0FBUyxDQUFDNkIsSUFBSSxHQUFHLFlBQVk7TUFDN0I3QixTQUFTLENBQUM4QixFQUFFLEdBQUcsWUFBWTtNQUMzQjlCLFNBQVMsQ0FBQ1ksSUFBSSxHQUFHLE1BQU07TUFDdkIsSUFBR1cscUJBQXFCLEVBQUM7UUFDckJ2QixTQUFTLENBQUMrQixNQUFNLEdBQUdSLHFCQUFxQjtNQUM1QztNQUNBdkIsU0FBUyxDQUFDZ0MsUUFBUSxHQUFHLEtBQUs7TUFDMUJoQyxTQUFTLENBQUNpQyxRQUFRLEdBQUdDLGdCQUFnQjtNQUNyQy9CLFFBQVEsQ0FBQ0MsSUFBSSxDQUFDK0IsV0FBVyxDQUFDbkMsU0FBUyxDQUFDO01BQ3BDQSxTQUFTLENBQUNULGdCQUFnQixDQUFDLFFBQVEsRUFBRSxNQUFNbkUsT0FBTyxDQUFDLGlCQUFpQixDQUFDLENBQUM7TUFDdEU0RSxTQUFTLENBQUNvQyxLQUFLLENBQUMsQ0FBQzs7TUFFakI7TUFDQSxTQUFTRixnQkFBZ0JBLENBQUNyRCxLQUFLLEVBQUU7UUFDN0JhLFdBQVcsR0FBRyxJQUFJO1FBRWxCLE1BQU0yQyxPQUFPLEdBQUd4RCxLQUFLLENBQUN5RCxNQUFNLENBQUNDLEtBQUssQ0FBQyxDQUFDLENBQUM7UUFDckMsTUFBTXRDLFVBQVUsR0FBR3hFLEVBQUUsQ0FBQzhCLEVBQUUsQ0FBQ2lGLFlBQVksQ0FBQyxJQUFJLEVBQUUsSUFBSSxDQUFDOztRQUVqRDtRQUNBLElBQUksQ0FBQ2xDLGlCQUFpQixDQUFDO1VBQUNFLGFBQWEsRUFBRVIsU0FBUyxDQUFDK0IsTUFBTTtVQUFFdEIsUUFBUSxFQUFFNEIsT0FBTyxDQUFDekI7UUFBSSxDQUFDLENBQUMsRUFBRTtVQUMvRWQsaUJBQWlCLENBQUM7WUFBQ0UsU0FBUztZQUFFQztVQUFVLENBQUMsQ0FBQztVQUMxQzdFLE9BQU8sQ0FBQyxxQkFBcUIsQ0FBQztVQUM5QjtRQUNKO1FBQ0E7UUFDQSxJQUFJLENBQUMyRixnQkFBZ0IsQ0FBQztVQUFDRSxZQUFZLEVBQUVvQixPQUFPO1VBQUVuQixPQUFPLEVBQUVNO1FBQTBCLENBQUMsQ0FBQyxFQUFFO1VBQ2pGMUIsaUJBQWlCLENBQUM7WUFBQ0UsU0FBUztZQUFFQztVQUFVLENBQUMsQ0FBQztVQUMxQzdFLE9BQU8sQ0FBQyxxQkFBcUIsQ0FBQztVQUM5QjtRQUNKO1FBQ0E7UUFDQXVFLDBCQUEwQixDQUFDMEMsT0FBTyxDQUFDLENBQUNoSSxJQUFJLENBQUVpRSxXQUFXLElBQUs7VUFDdEQsSUFBR0EsV0FBVyxJQUFJLE9BQU9BLFdBQVcsS0FBSyxRQUFRLEVBQUU7WUFDL0N3QixpQkFBaUIsQ0FBQztjQUFDRSxTQUFTO2NBQUVDO1lBQVUsQ0FBQyxDQUFDO1lBQzFDN0UsT0FBTyxDQUFDa0QsV0FBVyxDQUFDO1VBQ3hCLENBQUMsTUFBTTtZQUNId0IsaUJBQWlCLENBQUM7Y0FBQ0UsU0FBUztjQUFFQztZQUFVLENBQUMsQ0FBQztZQUMxQzdFLE9BQU8sQ0FBQyxrQkFBa0IsQ0FBQztVQUMvQjtRQUNKLENBQUMsQ0FBQztRQUNGO01BQ0o7TUFBQztJQUNMLENBQUMsQ0FBQyxPQUFPVSxLQUFLLEVBQUU7TUFDWjVCLE1BQU0sQ0FBQzRCLEtBQUssQ0FBQztJQUNqQjtFQUNKLENBQUMsQ0FBQztFQUNMO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNoSEE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDNkI7QUFDb0M7O0FBRWpFO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ08sZUFBZTJHLG9CQUFvQkEsQ0FBQzFJLEdBQUcsRUFBRVEsS0FBSyxFQUFFO0VBQ3REO0VBQ0csSUFBSSxDQUFDUixHQUFHLEVBQUU7SUFDTixPQUFPRSxPQUFPLENBQUNDLE1BQU0sQ0FBQyxJQUFJQyxLQUFLLENBQUMsbUNBQW1DLENBQUMsQ0FBQztFQUN6RTtFQUNBLElBQUksQ0FBQ0ksS0FBSyxFQUFFO0lBQ1IsT0FBT04sT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLHFDQUFxQyxDQUFDLENBQUM7RUFDM0U7RUFDQSxNQUFNdUksZ0JBQWdCLEdBQUc3SCxpQkFBaUIsQ0FBQ04sS0FBSyxDQUFDO0VBQ2pELE9BQU9PLE9BQU8sQ0FBQ2YsR0FBRyxFQUFFUyxJQUFJLENBQUNPLFNBQVMsQ0FBQzJILGdCQUFnQixDQUFDLENBQUM7RUFDckQsU0FBUzVILE9BQU9BLENBQUNmLEdBQUcsRUFBRVEsS0FBSyxFQUFFO0lBQ3pCLElBQUlTLFNBQVMsSUFBSUEsU0FBUyxDQUFDQyxPQUFPLEtBQUssYUFBYSxFQUFFO01BQ2xELE9BQU9wQixvRkFBb0IsQ0FBQ0UsR0FBRyxFQUFFUSxLQUFLLENBQUM7SUFDM0M7SUFDQSxJQUFJVyxNQUFNLEVBQUU7TUFDUkEsTUFBTSxDQUFDQyxZQUFZLENBQUNMLE9BQU8sQ0FBQ2YsR0FBRyxFQUFFUSxLQUFLLENBQUM7TUFDdkMsT0FBT04sT0FBTyxDQUFDbUIsT0FBTyxDQUFDLENBQUM7SUFDNUI7SUFDQSxPQUFPbkIsT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLDBCQUEwQixDQUFDLENBQUM7RUFDaEU7RUFDQSxTQUFTVSxpQkFBaUJBLENBQUMyQixNQUFNLEVBQUU7SUFDL0IsT0FBT0EsTUFBTSxDQUFDQyxhQUFhLENBQUMsQ0FBQyxDQUFDQyxNQUFNLENBQUMsQ0FBQ0MsV0FBVyxFQUFFTixhQUFhLEtBQUs7TUFDakVNLFdBQVcsQ0FBQ04sYUFBYSxDQUFDLEdBQUdHLE1BQU0sQ0FBQ2IsR0FBRyxDQUFDVSxhQUFhLENBQUM7TUFDdEQsT0FBT00sV0FBVztJQUN0QixDQUFDLEVBQUU7TUFBRXJCLElBQUksRUFBRWtCLE1BQU0sQ0FBQ0ksT0FBTyxDQUFDO0lBQUUsQ0FBQyxDQUFDO0VBQ2xDO0VBQ0g7QUFDRDs7Ozs7Ozs7Ozs7QUM5Q0E7Ozs7Ozs7Ozs7QUNBQTs7Ozs7O1VDQUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTs7VUFFQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTs7Ozs7V0N0QkE7V0FDQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLGlDQUFpQyxXQUFXO1dBQzVDO1dBQ0E7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx5Q0FBeUMsd0NBQXdDO1dBQ2pGO1dBQ0E7V0FDQTs7Ozs7V0NQQTs7Ozs7V0NBQTtXQUNBO1dBQ0E7V0FDQSx1REFBdUQsaUJBQWlCO1dBQ3hFO1dBQ0EsZ0RBQWdELGFBQWE7V0FDN0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ05PLE1BQU0rRiwwQ0FBMEMsR0FBRyxNQUFBQSxDQUFBLEtBQVksQ0FBQyxNQUFNLDZYQUF3SSxFQUFFaEYsMkJBQTJCO0FBQzNPLE1BQU1pRixtQ0FBbUMsR0FBRyxNQUFBQSxDQUFBLEtBQVksQ0FBQyxNQUFNLCtXQUFpSSxFQUFFSCxvQkFBb0I7QUFDdE4sTUFBTUksZ0RBQWdELEdBQUcsTUFBQUEsQ0FBQSxLQUFZLENBQUMsTUFBTSx5WUFBOEksRUFBRXBELGlDQUFpQztBQUM3UCxNQUFNcUQsK0NBQStDLEdBQUcsTUFBQUEsQ0FBQSxLQUFZLENBQUMsTUFBTSx1WUFBNkksRUFBRXhCLGdDQUFnQztBQUMxUCxNQUFNeUIsOENBQThDLEdBQUcsTUFBQUEsQ0FBQSxLQUFZLENBQUMsTUFBTSxxWUFBNEksRUFBRWpFLCtCQUErQjtBQUN2UCxNQUFNa0UsOENBQThDLEdBQUcsTUFBQUEsQ0FBQSxLQUFZLENBQUMsTUFBTSxxWUFBNEksRUFBRTNFLCtCQUErQjtBQUN2UCxNQUFNNEUsbUNBQW1DLEdBQUcsTUFBQUEsQ0FBQSxLQUFZLENBQUMsTUFBTSwrV0FBaUksRUFBRW5KLG9CQUFvQixDIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vL0ByZWFjdC1uYXRpdmUtY29tbXVuaXR5L2FzeW5jLXN0b3JhZ2UiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL0dldFN0b3JhZ2VJdGVtT2JqZWN0LmpzIiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy96Zl9rYXJheW1laC9Qcm9qZWN0cy9uYXRpdmVDYXJkV2FsbGV0L3Rlc3RQcm9qZWN0L2phdmFzY3JpcHRzb3VyY2UvZmVlZGJhY2ttb2R1bGUvYWN0aW9ucy9KU19Qb3B1bGF0ZUZlZWRiYWNrTWV0YWRhdGEuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL0pTX1Jldm9rZVVwbG9hZGVkRmlsZUZyb21NZW1vcnkuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL0pTX1RvZ2dsZUZlZWRiYWNrQW5ub3RhdGVXaWRnZXQuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL0pTX1RvZ2dsZUZlZWRiYWNrU2NyZWVuc2hvdFdpZGdldC5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvemZfa2FyYXltZWgvUHJvamVjdHMvbmF0aXZlQ2FyZFdhbGxldC90ZXN0UHJvamVjdC9qYXZhc2NyaXB0c291cmNlL2ZlZWRiYWNrbW9kdWxlL2FjdGlvbnMvSlNfVXBsb2FkQW5kQ29udmVydFRvRmlsZUJsb2JVUkwuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL1NldFN0b3JhZ2VJdGVtT2JqZWN0LmpzIiwid2VicGFjazovLy9leHRlcm5hbCBhbWQgXCJiaWcuanNcIiIsIndlYnBhY2s6Ly8vbXgtZ2xvYmFsIiwid2VicGFjazovLy93ZWJwYWNrL2Jvb3RzdHJhcCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2NvbXBhdCBnZXQgZGVmYXVsdCBleHBvcnQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9kZWZpbmUgcHJvcGVydHkgZ2V0dGVycyIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2hhc093blByb3BlcnR5IHNob3J0aGFuZCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL21ha2UgbmFtZXNwYWNlIG9iamVjdCIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvemZfa2FyYXltZWgvUHJvamVjdHMvbmF0aXZlQ2FyZFdhbGxldC90ZXN0UHJvamVjdC9kZXBsb3ltZW50L3RtcC9qc2FjdGlvbnMuanMiXSwic291cmNlc0NvbnRlbnQiOlsiLyogZW1wdHkgKi8iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgXCJteC1nbG9iYWxcIjtcclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5pbXBvcnQgQXN5bmNTdG9yYWdlIGZyb20gJ0ByZWFjdC1uYXRpdmUtY29tbXVuaXR5L2FzeW5jLXN0b3JhZ2UnO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIFdoYXQgZG9lcyB0aGlzIEphdmFTY3JpcHQgYWN0aW9uIGRvP1xyXG4gKiBcclxuICogR2V0IGxvY2FsbHkgc3RvcmVkIEpTT04gb2JqZWN0IHN0b3JlZCBpbiBjbGllbnRzIGludGVybmV0IGJyb3dzZXIuIElkZW50aWZpZWQgYnkgYSB1bmlxdWUga2V5LiBDYW4gYmUgYWNjZXNzZWQgYnkgdGhlIEdldFN0b3JhZ2VJdGVtT2JqZWN0IGFjdGlvbi4gUGxlYXNlIG5vdGUgdGhhdCB1c2VycyBjYW4gY2xlYXIgdGhlIGRldmljZSBzdG9yYWdlLlxyXG4gKiBAcGFyYW0ge3N0cmluZ30ga2V5IC0gVGhpcyBmaWVsZCBpcyByZXF1aXJlZC5cclxuICogQHBhcmFtIHtzdHJpbmd9IGVudGl0eSAtIFRoaXMgZmllbGQgaXMgcmVxdWlyZWQuXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjxNeE9iamVjdD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gR2V0U3RvcmFnZUl0ZW1PYmplY3Qoa2V5LCBlbnRpdHkpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuICAgIGlmICgha2V5KSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIklucHV0IHBhcmFtZXRlciAnS2V5JyBpcyByZXF1aXJlZFwiKSk7XHJcbiAgICB9XHJcbiAgICBpZiAoIWVudGl0eSkge1xyXG4gICAgICAgIHJldHVybiBQcm9taXNlLnJlamVjdChuZXcgRXJyb3IoXCJJbnB1dCBwYXJhbWV0ZXIgJ0VudGl0eScgaXMgcmVxdWlyZWRcIikpO1xyXG4gICAgfVxyXG4gICAgcmV0dXJuIGdldEl0ZW0oa2V5KS50aGVuKHJlc3VsdCA9PiB7XHJcbiAgICAgICAgaWYgKHJlc3VsdCA9PT0gbnVsbCkge1xyXG4gICAgICAgICAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKGBTdG9yYWdlIGl0ZW0gJyR7a2V5fScgZG9lcyBub3QgZXhpc3RgKSk7XHJcbiAgICAgICAgfVxyXG4gICAgICAgIGNvbnN0IHZhbHVlID0gSlNPTi5wYXJzZShyZXN1bHQpO1xyXG4gICAgICAgIHJldHVybiBnZXRPckNyZWF0ZU14T2JqZWN0KGVudGl0eSwgdmFsdWUpLnRoZW4obmV3T2JqZWN0ID0+IHtcclxuICAgICAgICAgICAgY29uc3QgbmV3VmFsdWUgPSBzZXJpYWxpemVNeE9iamVjdChuZXdPYmplY3QpO1xyXG4gICAgICAgICAgICByZXR1cm4gc2V0SXRlbShrZXksIEpTT04uc3RyaW5naWZ5KG5ld1ZhbHVlKSkudGhlbigoKSA9PiBuZXdPYmplY3QpO1xyXG4gICAgICAgIH0pO1xyXG4gICAgfSk7XHJcbiAgICBmdW5jdGlvbiBnZXRJdGVtKGtleSkge1xyXG4gICAgICAgIGlmIChuYXZpZ2F0b3IgJiYgbmF2aWdhdG9yLnByb2R1Y3QgPT09IFwiUmVhY3ROYXRpdmVcIikge1xyXG4gICAgICAgICAgICByZXR1cm4gQXN5bmNTdG9yYWdlLmdldEl0ZW0oa2V5KTtcclxuICAgICAgICB9XHJcbiAgICAgICAgaWYgKHdpbmRvdykge1xyXG4gICAgICAgICAgICBjb25zdCB2YWx1ZSA9IHdpbmRvdy5sb2NhbFN0b3JhZ2UuZ2V0SXRlbShrZXkpO1xyXG4gICAgICAgICAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKHZhbHVlKTtcclxuICAgICAgICB9XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIk5vIHN0b3JhZ2UgQVBJIGF2YWlsYWJsZVwiKSk7XHJcbiAgICB9XHJcbiAgICBmdW5jdGlvbiBzZXRJdGVtKGtleSwgdmFsdWUpIHtcclxuICAgICAgICBpZiAobmF2aWdhdG9yICYmIG5hdmlnYXRvci5wcm9kdWN0ID09PSBcIlJlYWN0TmF0aXZlXCIpIHtcclxuICAgICAgICAgICAgcmV0dXJuIEFzeW5jU3RvcmFnZS5zZXRJdGVtKGtleSwgdmFsdWUpO1xyXG4gICAgICAgIH1cclxuICAgICAgICBpZiAod2luZG93KSB7XHJcbiAgICAgICAgICAgIHdpbmRvdy5sb2NhbFN0b3JhZ2Uuc2V0SXRlbShrZXksIHZhbHVlKTtcclxuICAgICAgICAgICAgcmV0dXJuIFByb21pc2UucmVzb2x2ZSgpO1xyXG4gICAgICAgIH1cclxuICAgICAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwiTm8gc3RvcmFnZSBBUEkgYXZhaWxhYmxlXCIpKTtcclxuICAgIH1cclxuICAgIGZ1bmN0aW9uIGdldE9yQ3JlYXRlTXhPYmplY3QoZW50aXR5LCB2YWx1ZSkge1xyXG4gICAgICAgIHJldHVybiBnZXRNeE9iamVjdCh2YWx1ZS5ndWlkKS50aGVuKGV4aXN0aW5nT2JqZWN0ID0+IHtcclxuICAgICAgICAgICAgaWYgKGV4aXN0aW5nT2JqZWN0KSB7XHJcbiAgICAgICAgICAgICAgICByZXR1cm4gZXhpc3RpbmdPYmplY3Q7XHJcbiAgICAgICAgICAgIH1cclxuICAgICAgICAgICAgZWxzZSB7XHJcbiAgICAgICAgICAgICAgICByZXR1cm4gY3JlYXRlTXhPYmplY3QoZW50aXR5LCB2YWx1ZSk7XHJcbiAgICAgICAgICAgIH1cclxuICAgICAgICB9KTtcclxuICAgIH1cclxuICAgIGZ1bmN0aW9uIGdldE14T2JqZWN0KGd1aWQpIHtcclxuICAgICAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xyXG4gICAgICAgICAgICBteC5kYXRhLmdldCh7XHJcbiAgICAgICAgICAgICAgICBndWlkLFxyXG4gICAgICAgICAgICAgICAgY2FsbGJhY2s6IG14T2JqZWN0ID0+IHJlc29sdmUobXhPYmplY3QpLFxyXG4gICAgICAgICAgICAgICAgZXJyb3I6IGVycm9yID0+IHJlamVjdChlcnJvcilcclxuICAgICAgICAgICAgfSk7XHJcbiAgICAgICAgfSk7XHJcbiAgICB9XHJcbiAgICBmdW5jdGlvbiBjcmVhdGVNeE9iamVjdChlbnRpdHksIHZhbHVlKSB7XHJcbiAgICAgICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcclxuICAgICAgICAgICAgbXguZGF0YS5jcmVhdGUoe1xyXG4gICAgICAgICAgICAgICAgZW50aXR5LFxyXG4gICAgICAgICAgICAgICAgY2FsbGJhY2s6IG14T2JqZWN0ID0+IHtcclxuICAgICAgICAgICAgICAgICAgICBPYmplY3Qua2V5cyh2YWx1ZSlcclxuICAgICAgICAgICAgICAgICAgICAgICAgLmZpbHRlcihhdHRyaWJ1dGUgPT4gYXR0cmlidXRlICE9PSBcImd1aWRcIilcclxuICAgICAgICAgICAgICAgICAgICAgICAgLmZvckVhY2goYXR0cmlidXRlTmFtZSA9PiB7XHJcbiAgICAgICAgICAgICAgICAgICAgICAgIGNvbnN0IGF0dHJpYnV0ZVZhbHVlID0gdmFsdWVbYXR0cmlidXRlTmFtZV07XHJcbiAgICAgICAgICAgICAgICAgICAgICAgIG14T2JqZWN0LnNldChhdHRyaWJ1dGVOYW1lLCBhdHRyaWJ1dGVWYWx1ZSk7XHJcbiAgICAgICAgICAgICAgICAgICAgfSk7XHJcbiAgICAgICAgICAgICAgICAgICAgcmVzb2x2ZShteE9iamVjdCk7XHJcbiAgICAgICAgICAgICAgICB9LFxyXG4gICAgICAgICAgICAgICAgZXJyb3I6ICgpID0+IHJlamVjdChuZXcgRXJyb3IoYENvdWxkIG5vdCBjcmVhdGUgJyR7ZW50aXR5fScgb2JqZWN0YCkpXHJcbiAgICAgICAgICAgIH0pO1xyXG4gICAgICAgIH0pO1xyXG4gICAgfVxyXG4gICAgZnVuY3Rpb24gc2VyaWFsaXplTXhPYmplY3Qob2JqZWN0KSB7XHJcbiAgICAgICAgcmV0dXJuIG9iamVjdC5nZXRBdHRyaWJ1dGVzKCkucmVkdWNlKChhY2N1bXVsYXRvciwgYXR0cmlidXRlTmFtZSkgPT4ge1xyXG4gICAgICAgICAgICBhY2N1bXVsYXRvclthdHRyaWJ1dGVOYW1lXSA9IG9iamVjdC5nZXQoYXR0cmlidXRlTmFtZSk7XHJcbiAgICAgICAgICAgIHJldHVybiBhY2N1bXVsYXRvcjtcclxuICAgICAgICB9LCB7IGd1aWQ6IG9iamVjdC5nZXRHdWlkKCkgfSk7XHJcbiAgICB9XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCBcIm14LWdsb2JhbFwiO1xyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbiAgICBjb25zdCBoYW5kbGVVc2VyUm9sZXMgPSBhc3luYyAoKSA9PiB7XHJcbiAgICAgICAgaWYoIW14KSByZXR1cm4gdW5kZWZpbmVkO1xyXG4gICAgICAgIHRyeSB7XHJcbiAgICAgICAgICAgIHJldHVybiBhd2FpdCBteC5zZXNzaW9uLmdldFVzZXJSb2xlTmFtZXMoKTtcclxuICAgICAgICB9IGNhdGNoIChlcnJvcil7XHJcbiAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoXCJFcnJvciBnZXR0aW5nIHVzZXIgcm9sZSBuYW1lc1wiLCBlcnJvcik7XHJcbiAgICAgICAgICAgIHJldHVybiB1bmRlZmluZWQ7XHJcbiAgICAgICAgfVxyXG4gICAgfTtcclxuICAgIGNvbnN0IGhhbmRsZVBhZ2VQYXRoID0gYXN5bmMgKCkgPT4ge1xyXG4gICAgICAgICAgICBpZighbXgpIHJldHVybiB1bmRlZmluZWQ7XHJcbiAgICAgICAgICAgIHRyeSB7XHJcbiAgICAgICAgICAgICAgICBjb25zdCBtZW5kaXhWZXJzaW9uID0gbXgudmVyc2lvblxyXG4gICAgICAgICAgICAgICAgY29uc3QgbWVuZGl4TWFqb3JWZXJzaW9uID0gbWVuZGl4VmVyc2lvbi5zcGxpdCgnLicpWzBdO1xyXG4gICAgICAgICAgICAgICAgc3dpdGNoKG1lbmRpeE1ham9yVmVyc2lvbikge1xyXG4gICAgICAgICAgICAgICAgICAgIGNhc2UgJzknOlxyXG4gICAgICAgICAgICAgICAgICAgIGNhc2UgJzEwJzpcclxuICAgICAgICAgICAgICAgICAgICAgICAgcmV0dXJuIG14LnVpLmdldENvbnRlbnRGb3JtKCkucGF0aC50b1N0cmluZygpO1xyXG4gICAgICAgICAgICAgICAgICAgIGRlZmF1bHQ6XHJcbiAgICAgICAgICAgICAgICAgICAgICAgIHJldHVybiB1bmRlZmluZWQ7XHJcbiAgICAgICAgICAgICAgICB9O1xyXG4gICAgICAgICAgICB9IGNhdGNoIHtcclxuICAgICAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoXCJFcnJvciBnZXR0aW5nIHBhZ2UgcGF0aFwiLCBlcnJvcik7XHJcbiAgICAgICAgICAgICAgICByZXR1cm4gdW5kZWZpbmVkXHJcbiAgICAgICAgICAgIH1cclxuICAgIH07XHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogV2hhdCBkb2VzIHRoaXMgSmF2YVNjcmlwdCBhY3Rpb24gZG8/XHJcbiAqIFxyXG4gKiBSZXR1cm5zIG1ldGEgZGF0YSBmcm9tIHRoZSBjbGllbnRzIGludGVybmV0IGJyb3dzZXIuIFxyXG4gKiBcclxuICogVGhpcyBpbmNsdWRlczsgXHJcbiAqIFxyXG4gKiBBY3RpdmVVc2VyUm9sZXNcclxuICogUGFnZU5hbWVcclxuICogRW52aXJvbm1lbnRVUkxcclxuICogQnJvd3NlclxyXG4gKiBTY3JlZW5XaWR0aFxyXG4gKiBTY3JlZW5IZWlnaHRcclxuICogQHBhcmFtIHtNeE9iamVjdH0gZmVlZGJhY2tcclxuICogQHJldHVybnMge1Byb21pc2UuPE14T2JqZWN0Pn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19Qb3B1bGF0ZUZlZWRiYWNrTWV0YWRhdGEoZmVlZGJhY2spIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuICAgIHRyeSB7XHJcbiAgICAgICAgY29uc3QgdXNlclJvbGVzID0gYXdhaXQgaGFuZGxlVXNlclJvbGVzKCk7XHJcbiAgICAgICAgY29uc3QgcGFnZVBhdGggPSBhd2FpdCBoYW5kbGVQYWdlUGF0aCgpO1xyXG4gICAgICAgIGZlZWRiYWNrLnNldChcIkFjdGl2ZVVzZXJSb2xlc1wiLCB1c2VyUm9sZXMpO1xyXG4gICAgICAgIGZlZWRiYWNrLnNldChcIlBhZ2VOYW1lXCIsIHBhZ2VQYXRoKTtcclxuICAgICAgICBmZWVkYmFjay5zZXQoXCJFbnZpcm9ubWVudFVSTFwiLCB3aW5kb3cubG9jYXRpb24uaHJlZik7XHJcbiAgICAgICAgZmVlZGJhY2suc2V0KFwiQnJvd3NlclwiLCBuYXZpZ2F0b3IudXNlckFnZW50KTtcclxuICAgICAgICBmZWVkYmFjay5zZXQoXCJTY3JlZW5XaWR0aFwiLCB3aW5kb3cuc2NyZWVuLndpZHRoKTtcclxuICAgICAgICBmZWVkYmFjay5zZXQoXCJTY3JlZW5IZWlnaHRcIiwgd2luZG93LnNjcmVlbi5oZWlnaHQpO1xyXG4gICAgICAgIHJldHVybiBmZWVkYmFjaztcclxuICAgIH0gY2F0Y2ggKGVycm9yKSB7XHJcbiAgICAgICAgY29uc29sZS5lcnJvcihcIkVycm9yIHNldHRpbmcgbWV0YSBkYXRhXCIsIGVycm9yKTtcclxuICAgIH1cclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IFwibXgtZ2xvYmFsXCI7XHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBXaGF0IGRvZXMgdGhpcyBKYXZhU2NyaXB0IGFjdGlvbiBkbz9cclxuICogXHJcbiAqIEFmdGVyIHlvdSBoYXZlIHVwbG9hZGVkIGFuIGltYWdlIGl0IHJlbW92ZXMgbG9jYWxseSBzdG9yZWQgaW1hZ2UgZnJvbSBtZW1vcnkuIFRoaXMgaXMgYSBjdXN0b20gYnVpbGQgYWN0aW9uLlxyXG4gKiBcclxuICogRGVwZW5kZW5jeSBOb3RlOiBcclxuICogVGhpcyBKYXZhU2NyaXB0IGFjdGlvbiBzaG91bGQgYmUgdXNlZCBvbmx5IHdoZW4geW91IGhhdmUgaW5zZXJ0ZWQgdGhlIEltYWdlIFVwbG9hZCBKYXZhU2NyaXB0IEFjdGlvbiBjYWxsZWQgJ0pTX1VwbG9hZEFuZENvbnZlcnRUb0ZpbGVCbG9iVVJMJyBpbnRvIHlvdXIgbmFub2Zsb3cuXHJcbiAqIFxyXG4gKiBNb3JlIGRldGFpbGVkIGV4cGxhbmF0aW9uOiAgTWVtb3J5IG1hbmFnZW1lbnQuXHJcbiAqIFxyXG4gKiBUbyB1cGxvYWQgYSBpbWFnZSB3ZSB1c2UgYSBjdXN0b20gYnVpbGQgSmF2YXNjcmlwdCBhY3Rpb24gY2FsbGVkICAnSlNfVXBsb2FkQW5kQ29udmVydFRvRmlsZUJsb2JVUkwnLlxyXG4gKiBJbnNpZGUgdGhpcyBhY3Rpb24gd2UgdXNlIGEgSmF2YVNjcmlwdCBtZXRob2QgY2FsbGVkIGNyZWF0ZU9iamVjdFVSTCgpIHRvIHVwbG9hZCBhbmQgc3RvcmUgZmlsZXMgaW4gbG9jYWwgbWVtb3J5LiBXZSBjYW4gYWNjZXNzIGFuZCBjb3N1bWUgdGhpcyBpbiBtZW1vcnkgaW1hZ2UgcmVzb3VyY2UgdmlhIHRoZSBVUkwgcGF0aCB0aGF0IGlzIHJldHVybmVkIGZyb20gdGhlIGNyZWF0ZU9iamVjdFVSTCgpIG1ldGhvZC4gXHJcbiAqIFxyXG4gKiBIb3dldmVyLCBlYWNoIHRpbWUgeW91IGNhbGwgY3JlYXRlT2JqZWN0VVJMKCksIGEgbmV3IG9iamVjdCBpcyBjcmVhdGVkIGluIG1lbW9yeSwgZXZlbiBpZiB5b3UndmUgYWxyZWFkeSBjcmVhdGVkIG9uZSBmb3IgdGhlIHNhbWUgb2JqZWN0LiBcclxuICogU28gZWFjaCBvZiB0aGVzZSBtdXN0IGJlIHJlbGVhc2VkIGJ5IGNhbGxpbmcgdGhpcyBhY3Rpb24gY2FsbGVkICdKU19SZXZva2VVcGxvYWRlZEZpbGVGcm9tTWVtb3J5JyB3aGVuIHlvdSBubyBsb25nZXIgbmVlZCB0aGVtLlxyXG4gKiBcclxuICogQnJvd3NlcnMgd2lsbCByZWxlYXNlIG9iamVjdCBVUkxzIGF1dG9tYXRpY2FsbHkgd2hlbiB0aGUgZG9jdW1lbnQgaXMgdW5sb2FkZWQ7IGhvd2V2ZXIsIGZvciBvcHRpbWFsIHBlcmZvcm1hbmNlIGFuZCBtZW1vcnkgdXNhZ2UsIGlmIHRoZXJlIGFyZSBzYWZlIHRpbWVzIHdoZW4geW91IGNhbiBleHBsaWNpdGx5IHVubG9hZCB0aGVtLCB5b3Ugc2hvdWxkIGRvIHNvIHdpdGggdGhlIEphdmFTY3JpcHRBY3Rpb24gY2FsbGVkICdKU19SZXZva2VVcGxvYWRlZEZpbGVGcm9tTWVtb3J5Jy5cclxuICogQHBhcmFtIHtzdHJpbmd9IGZpbGVCbG9iVVJMIC0gWW91IGhhdmUgdG8gcGFzcyB0aGUgZmlsZUJsb2JVUkwgdGhhdCB3YXMgY3JlYXRlZCB1c2luZyB0aGUgVVJMLmNyZWF0ZU9iamVjdFVSTCgpIGluIHRoZSBKUyBBY3Rpb24gY2FsbGVkICdKU19VcGxvYWRBbmRDb252ZXJ0VG9GaWxlQmxvYlVSTCdcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEpTX1Jldm9rZVVwbG9hZGVkRmlsZUZyb21NZW1vcnkoZmlsZUJsb2JVUkwpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHQvKiBXZSB1c2UgdGhlIFVSTC5jcmVhdGVPYmplY3RVUkwoKSBzdGF0aWMgbWV0aG9kIHdoaWNoIGNyZWF0ZXMgYSBzdHJpbmcgY29udGFpbmluZyBhIFVSTCByZXByZXNlbnRpbmcgdGhlXHJcblx0ICAgaW1hZ2UgdXBsb2FkZWQuIFxyXG5cdCAgIFRoZSBpbWFnZSBibG9iIGlzIHN0b3JlZCBpbiB0aGUgY2xpZW50cyBicm93c2VyIGFuZCB0YWtlcyB1cCBtZW1vcnkgd2hpbHN0IHRoZSBzZXNzaW9uIGlzIGFjdGl2ZS4gU28gaGVyZSB3ZSBcclxuXHQgICByZXZva2UgdGhlIGltYWdlIHdoZW4gdGhlIHVzZXIgZGVsZXRlcyB0aGUgaW1hZ2UuIE5vdGUgdGhhdCB0aGUgaW1hZ2UgaXMgYXV0b21hdGljbGx5IHJldm9rZWQgd2hlbiB0aGUgYnJvd3NlciByZWZyZXNoZXNcclxuXHQgICBvciBjbG9zZXMuXHJcblxyXG5cdCAgIFlvdSBoYXZlIHRvIHBhc3MgdGhlIGZpbGVCbG9iVVJMIHRoYXQgd2FzIGNyZWF0ZWQgdXNpbmcgdGhlIFVSTC5jcmVhdGVPYmplY3RVUkwoKSBpbiB0aGUgSlMgQWN0aW9uIGNhbGxlZCAnSlNfVXBsb2FkQW5kQ29udmVydFRvRmlsZUJsb2JVUkwnXHJcblx0ICovXHJcblx0aWYoZmlsZUJsb2JVUkwgJiYgdHlwZW9mIGZpbGVCbG9iVVJMID09PSBcInN0cmluZ1wiKXtcclxuXHRcdFVSTC5yZXZva2VPYmplY3RVUkwoZmlsZUJsb2JVUkwpO1xyXG5cdH0gZWxzZSB7XHJcblx0XHR0aHJvdyBuZXcgRXJyb3IoXCJJbWFnZSB3YXMgbm90IHJlbW92ZWQgZnJvbSBicm93c2VyIG1lbW9yeVwiKTtcclxuXHR9XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCBcIm14LWdsb2JhbFwiO1xyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIG1lc3NhZ2VBY3Rpb25UeXBlcyBhcmUgdG8gaWRlbnRpZnkgdGhlIHBvc3RNZXNzYWdlIHR5cGVzIGJldHdlZW4gdGhlIEpTIEFjdGlvbiAmIEZlZWRiYWNrIFdpZGdldC5cclxuY29uc3QgbWVzc2FnZUFjdGlvbl90b2dnbGVBbm5vdGF0ZU1vZGUgPSBcIm14RmVlZGJhY2tXaWRnZXRfdG9nZ2xlQW5ub3RhdGVNb2RlXCI7IC8vIFRoZSBGZWVkYmFjayB3aWRnZXQgcmVhZHMgdGhpcyB0byB0cmlnZ2VyIGEgc3BlY2lmaWMgc2NyZWVuc2hvdCBtb2RlIHN0YWdlLlxyXG5jb25zdCBtZXNzYWdlQWN0aW9uX2lzQmFzZTY0ID0gXCJteEZlZWRiYWNrV2lkZ2V0X2NvbnZlcnRlZFRvQmFzZTY0XCI7IC8vIFdlIGV4cGVjdCB0aGlzIHN0cmluZyBmcm9tIHRoZSB3aWRnZXQgd2hlbiBzY3JlZW5zaG90IG1vZGUgaW4gZW5hYmxlZC5cclxuY29uc3QgbWVzc2FnZUFjdGlvbl9hY3Rpb25DYW5jZWxsZWQgPSBcIm14RmVlZGJhY2tXaWRnZXRfYWN0aW9uQ2FuY2VsbGVkXCIgLy8gVGhlIEZlZWRiYWNrIHdpZGdldCB3aWxsIHNlbmQgdGhpcyBiYWNrIGlmIHNjcmVlbnNob3QvYW5ub3RhdGlvbiBhY3Rpb25zIGFyZSBjYW5jZWxsZWQgYnkgdGhlIHVzZXIuXHJcblxyXG5jb25zdCBwYXJzZUpTT04gPSAoZXZlbnQpID0+IHtcclxuXHR0cnkge1xyXG5cdFx0cmV0dXJuIEpTT04ucGFyc2UoZXZlbnQpO1xyXG5cdH0gY2F0Y2gge1xyXG5cdFx0cmV0dXJuIHVuZGVmaW5lZDtcclxuXHR9XHJcbn07XHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogV2hhdCBkb2VzIHRoaXMgSmF2YVNjcmlwdCBhY3Rpb24gZG8/XHJcbiAqIFxyXG4gKiBXaGVuIHlvdSB1cGxvYWQgYSBzY3JlZW5zaG90IG1hbnVhbGx5IHRoZSBpbWFnZSBjYW4gYmUgYW5ub3RhdGF0ZWQuIFxyXG4gKiBcclxuICogTW9yZSBkZXRhaWxlZCBleHBsYW5hdGlvbjpcclxuICogVGhlIE1lbmRpeCBGZWVkYmFjayBXaWRnZXQgaGFuZGxlcyBhbm5vdGF0aW9uIGFuZCBhbHNvIHJlbmRlcnMgYSBkZWZhdWx0IHN0eWxlZCBidXR0b24gb24geW91ciBwYWdlLiBcclxuICogXHJcbiAqIEluIG9yZGVyIHRvIHRyaWdnZXIgdGhlIGFubm90YXRpb24gbW9kZSB5b3UgaGF2ZSB0byB1c2UgdGhpcyBKYXZhU2NyaXB0IGFjdGlvbiB0byBzZW5kIHRoZSB3aWRnZXQgdGhlIGNvcnJlY3QgaW1hZ2UgcGF5bG9hZC5cclxuICogXHJcbiAqIFJldHVybiBUeXBlOlxyXG4gKiBXaWxsIHJldHVybiBiYXNlIDY0IGltYWdlIHN0cmluZ1xyXG4gKiBAcGFyYW0ge3N0cmluZ30gZmlsZUJsb2JVUkxcclxuICogQHJldHVybnMge1Byb21pc2UuPHN0cmluZz59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSlNfVG9nZ2xlRmVlZGJhY2tBbm5vdGF0ZVdpZGdldChmaWxlQmxvYlVSTCkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cdC8qIFxyXG5cdFRoZSB3aWRnZXQgYW5kIEpTIGFjdGlvbiBjb21tdW5pY2F0ZSB3aXRoIHRoZSBmb2xsb3dpbmcgcG9zdE1lc3NhZ2Ugb2JqZWN0IHN0cnVjdHVyZTpcclxuXHRtZXNzYWdlT2JqZWN0ID0ge21lc3NhZ2VBY3Rpb25UeXBlOiBzdHJpbmc7bWVzc2FnZURhdGE6IHN0cmluZzt9XHJcblx0Ki9cclxuXHRjb25zdCBtZXNzYWdlT2JqZWN0ID0ge1xyXG5cdFx0XCJtZXNzYWdlQWN0aW9uVHlwZVwiOiBtZXNzYWdlQWN0aW9uX3RvZ2dsZUFubm90YXRlTW9kZSwgLy8gVGhlIHdpZGdldCByZWFkcyB0aGlzIHRvIHRyaWdnZXIgdGhlIEFubm90YXRlIE1vZGUuXHJcblx0XHRcIm1lc3NhZ2VEYXRhXCI6IGZpbGVCbG9iVVJMIC8vIFRoZSB3aWRnZXQgdXNlcyB0aGlzIFVSTCByZWZlcmVuY2UgdG8gZ2V0IGFjY2VzcyB0byB0aGUgbG9jYWxseSBzdG9yZWQgaW1hZ2UgYmxvYi5cclxuXHR9O1xyXG5cclxuXHRwb3N0TWVzc2FnZShKU09OLnN0cmluZ2lmeShtZXNzYWdlT2JqZWN0KSwgd2luZG93Lm9yaWdpbik7IC8vIFNlbmQgdGhlIHNlcmlhbGl6ZWQgbWVzc2FnZSBvYmplY3QgdG8gRmVlZGJhY2sgV2lnZXQgdG8gdHJpZ2dlciBhbm5vdGF0ZSBtb2RlLlxyXG5cdFxyXG5cdHJldHVybiBuZXcgUHJvbWlzZShyZXNvbHZlID0+IHtcclxuXHRcdGZ1bmN0aW9uIGhhbmRsZUV2ZW50KGV2ZW50KSB7XHJcblx0XHRcdGNvbnN0IHBhcnNlZERhdGEgPSBwYXJzZUpTT04oZXZlbnQuZGF0YSk7IC8vIENvbnZlcnQgdGhlIHJlY2VpdmVkIHN0cmluZyB0byBhbiBvYmplY3QuXHJcblxyXG5cdFx0XHRpZihldmVudC5vcmlnaW4gPT09IHdpbmRvdy5vcmlnaW4pIHtcclxuXHRcdFx0XHRpZiAocGFyc2VkRGF0YSAmJiBwYXJzZWREYXRhLm1lc3NhZ2VBY3Rpb25UeXBlID09PSBtZXNzYWdlQWN0aW9uX2lzQmFzZTY0KSB7XHJcblx0XHRcdFx0XHR3aW5kb3cucmVtb3ZlRXZlbnRMaXN0ZW5lcihcIm1lc3NhZ2VcIiwgaGFuZGxlRXZlbnQpO1xyXG5cdFx0XHRcdFx0cmVzb2x2ZShwYXJzZWREYXRhLm1lc3NhZ2VEYXRhKTsgLy8gUmVzb2x2ZSAmIHJldHVybiB0aGUgYmFzZTY0IGltYWdlIHRvIHRoZSBuYW5vZmxvdy5cclxuXHRcdFx0XHR9O1xyXG5cdFx0XHRcdGlmKHBhcnNlZERhdGEgJiYgcGFyc2VkRGF0YS5tZXNzYWdlQWN0aW9uVHlwZSA9PT0gbWVzc2FnZUFjdGlvbl9hY3Rpb25DYW5jZWxsZWQpIHtcclxuXHRcdFx0XHRcdHJlc29sdmUoKTtcclxuXHRcdFx0XHR9XHJcblx0XHRcdH1cclxuXHJcblx0XHR9O1xyXG5cdFx0XHJcbiAgICAgICAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoXCJtZXNzYWdlXCIsIGhhbmRsZUV2ZW50KTsgLy8gTGlzdGVuIGFuZCB3YWl0IGZvciB0aGUgRmVlZGJhY2sgV2lkZ2V0IHRvIHNlbmQgdGhlIGJhc2U2NCBpbWFnZS5cclxuXHJcbiAgICB9KTtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IFwibXgtZ2xvYmFsXCI7XHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gbWVzc2FnZUFjdGlvblR5cGVzIGFyZSB0byBpZGVudGlmeSB0aGUgcG9zdE1lc3NhZ2UgdHlwZXMgYmV0d2VlbiB0aGUgSlMgQWN0aW9uICYgRmVlZGJhY2sgV2lkZ2V0LlxyXG5jb25zdCBtZXNzYWdlQWN0aW9uX3RvZ2dsZUFubm90YXRlTW9kZSA9IFwibXhGZWVkYmFja1dpZGdldF90b2dnbGVTY3JlZW5zaG90TW9kZVwiOyAvLyBUaGUgRmVlZGJhY2sgd2lkZ2V0IHJlYWRzIHRoaXMgdG8gdHJpZ2dlciBhIHNwZWNpZmljIHNjcmVlbnNob3QgbW9kZSBzdGFnZS5cclxuY29uc3QgbWVzc2FnZUFjdGlvbl9pc0Jhc2U2NCA9IFwibXhGZWVkYmFja1dpZGdldF9jb252ZXJ0ZWRUb0Jhc2U2NFwiOyAvLyBXZSBleHBlY3QgdGhpcyBzdHJpbmcgZnJvbSB0aGUgd2lkZ2V0IHdoZW4gc2NyZWVuc2hvdCBtb2RlIGluIGVuYWJsZWQuXHJcbmNvbnN0IG1lc3NhZ2VBY3Rpb25fYWN0aW9uQ2FuY2VsbGVkID0gXCJteEZlZWRiYWNrV2lkZ2V0X2FjdGlvbkNhbmNlbGxlZFwiIC8vIFRoZSBGZWVkYmFjayB3aWRnZXQgd2lsbCBzZW5kIHRoaXMgYmFjayBpZiBzY3JlZW5zaG90L2Fubm90YXRpb24gYWN0aW9ucyBhcmUgY2FuY2VsbGVkIGJ5IHRoZSB1c2VyLlxyXG5cclxuLyogXHJcblx0VGhlIHdpZGdldCBhbmQgSlMgYWN0aW9uIGNvbW11bmljYXRlIHdpdGggdGhlIGZvbGxvd2luZyBwb3N0TWVzc2FnZSBvYmplY3Qgc3RydWN0dXJlOlxyXG5cdG1lc3NhZ2VPYmplY3QgPSB7bWVzc2FnZUFjdGlvblR5cGU6IHN0cmluZzttZXNzYWdlRGF0YTogc3RyaW5nO31cclxuKi9cclxuY29uc3QgbWVzc2FnZU9iamVjdCA9IHtcclxuXHRcIm1lc3NhZ2VBY3Rpb25UeXBlXCI6IG1lc3NhZ2VBY3Rpb25fdG9nZ2xlQW5ub3RhdGVNb2RlIC8vVGhlIEZlZWRiYWNrIHdpZGdldCByZWFkcyB0aGlzIHRvIHRyaWdnZXIgYSBzcGVjaWZpYyBNb2RlLlxyXG59O1xyXG5cclxuY29uc3QgcGFyc2VKc29uID0gKGV2ZW50KSA9PiB7XHJcblx0dHJ5IHtcclxuXHRcdHJldHVybiBKU09OLnBhcnNlKGV2ZW50KTtcclxuXHR9IGNhdGNoIHtcclxuXHRcdHJldHVybiB1bmRlZmluZWQ7XHJcblx0fVxyXG59O1xyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIFdoYXQgZG9lcyB0aGlzIEphdmFTY3JpcHQgYWN0aW9uIGRvP1xyXG4gKiBcclxuICogTGV0cyB0byB0YWtlIGEgc2NyZWVuc2hvdCBvZiB0aGUgY3VycmVudCB2aXNpYmxlIHBhZ2VcclxuICogXHJcbiAqIE1vcmUgZGV0YWlsZWQgZXhwbGFuYXRpb246XHJcbiAqIFRoZSBNZW5kaXggRmVlZGJhY2sgV2lkZ2V0IGhhbmRsZXMgYW5ub3RhdGlvbiwgc2NyZWVuc2hvdCBhbmQgYWxzbyByZW5kZXJzIGEgZGVmYXVsdCBzdHlsZWQgYnV0dG9uIG9uIHlvdXIgcGFnZS4gXHJcbiAqIFxyXG4gKiBVc2FnZTpcclxuICogWW91IHNob3VsZCB1c2UgdGhpcyBKYXZhU2NyaXB0IGFjdGlvbiB0byB0cmlnZ2VyIHRoZSBzY3JlZW5zaG90IGZ1bmN0aW9uYWxpdHkuXHJcbiAqIFxyXG4gKiBSZXR1cm4gVHlwZTpcclxuICogV2lsbCByZXR1cm4gYSBpbWFnZSBiYXNlNjQgc3RyaW5nXHJcbiAqIFxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48c3RyaW5nPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19Ub2dnbGVGZWVkYmFja1NjcmVlbnNob3RXaWRnZXQoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0ICAgIHBvc3RNZXNzYWdlKEpTT04uc3RyaW5naWZ5KG1lc3NhZ2VPYmplY3QpLCB3aW5kb3cub3JpZ2luKTsgLy8gU2VuZCBhIG1lc3NhZ2UgdG8gdGhlIEZlZWRiYWNrIFdpZ2V0IHRvIHRyaWdnZXIgc2NyZWVuc2hvdCBtb2RlLlxyXG5cdFx0XHJcblx0XHRyZXR1cm4gbmV3IFByb21pc2UocmVzb2x2ZSA9PiB7XHJcblxyXG5cdFx0XHRmdW5jdGlvbiBoYW5kbGVFdmVudChldmVudCl7XHJcblx0XHRcdFx0Y29uc3QgcGFyc2VkRGF0YSA9IHBhcnNlSnNvbihldmVudC5kYXRhKTtcclxuXHRcdFx0XHRpZihwYXJzZWREYXRhICYmIGV2ZW50Lm9yaWdpbiA9PT0gd2luZG93Lm9yaWdpbikge1xyXG5cdFx0XHRcdFx0aWYgKHBhcnNlZERhdGEubWVzc2FnZUFjdGlvblR5cGUgPT09IG1lc3NhZ2VBY3Rpb25faXNCYXNlNjQpIHtcclxuXHRcdFx0XHRcdFx0d2luZG93LnJlbW92ZUV2ZW50TGlzdGVuZXIoXCJtZXNzYWdlXCIsIGhhbmRsZUV2ZW50KTtcclxuXHRcdFx0XHRcdFx0cmVzb2x2ZShwYXJzZWREYXRhLm1lc3NhZ2VEYXRhKTsgLy8gUmVzb2x2ZSAmIHJldHVybiB0aGUgYmFzZTY0IGltYWdlIHRvIHRoZSBuYW5vZmxvdy5cclxuXHRcdFx0XHRcdH07XHJcblx0XHRcdFx0XHRpZihwYXJzZWREYXRhLm1lc3NhZ2VBY3Rpb25UeXBlID09PSBtZXNzYWdlQWN0aW9uX2FjdGlvbkNhbmNlbGxlZCl7XHJcblx0XHRcdFx0XHRcdHJlc29sdmUoXCJ1cGxvYWRDYW5jZWxsZWRcIik7XHJcblx0XHRcdFx0XHR9XHJcblx0XHRcdFx0fVxyXG5cdFx0XHR9O1xyXG5cclxuXHRcdFx0d2luZG93LmFkZEV2ZW50TGlzdGVuZXIoXCJtZXNzYWdlXCIsIGhhbmRsZUV2ZW50KTsgLy8gTGlzdGVuIGFuZCB3YWl0IGZvciB0aGUgRmVlZGJhY2sgV2lkZ2V0IHRvIHNlbmQgYmFjayB0aGUgZWRpdGVkIHNjcmVlbnNob3QgYXMgYmFzZTY0LlxyXG5cclxuICAgIH0pO1xyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcbmltcG9ydCBcIm14LWdsb2JhbFwiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4gICAgdmFyIGlzVXBsb2FkaW5nID0gZmFsc2U7XHJcblxyXG7CoCDCoCBhc3luYyBmdW5jdGlvbiBzdG9yZUZpbGVBbmRHZXRSZXNvdXJjZVVybChmaWxlKSB7XHJcbsKgIMKgIMKgIMKgIHJldHVybiBVUkwuY3JlYXRlT2JqZWN0VVJMKGZpbGUpOyAvLyBTYXZlcyB0aGUgZmlsZSB0byBsb2NhbGx5IG1lbW9yeSBhbmQgcmV0dXJucyBhIFVSTCBwYXRoIHRvIHRoZSBCbG9iIG9iamVjdC5cclxuwqAgwqAgfTtcclxuXHJcbsKgIMKgIGZ1bmN0aW9uIHJlbW92ZURvbUVsZW1lbnRzKHtmaWxlSW5wdXQsIHByb2dyZXNzSWR9KSB7XHJcbsKgIMKgIMKgIMKgIGlmKHByb2dyZXNzSWQpIG14LnVpLmhpZGVQcm9ncmVzcyhwcm9ncmVzc0lkKTsgXHJcbsKgIMKgIMKgIMKgIGlmKGZpbGVJbnB1dCkgZG9jdW1lbnQuYm9keS5yZW1vdmVDaGlsZChmaWxlSW5wdXQpO1xyXG4gICAgICAgIGlzVXBsb2FkaW5nID0gZmFsc2U7IMKgIMKgXHJcbsKgIMKgIH1cclxuXHJcbsKgIMKgIGZ1bmN0aW9uIHZhbGlkYXRlRmlsZVR5cGVzICh7YWNjZXB0ZWRUeXBlcywgZmlsZVR5cGV9KSB7XHJcbsKgIMKgIMKgIMKgIGlmKCFhY2NlcHRlZFR5cGVzICYmICFmaWxlVHlwZSkgcmV0dXJuIGZhbHNlO1xyXG7CoCDCoCDCoCDCoCBjb25zdCBhY2NlcHRlZCA9IGFjY2VwdGVkVHlwZXMuc3BsaXQoXCIsXCIpO1xyXG7CoCDCoCDCoCDCoCByZXR1cm4gYWNjZXB0ZWQuc29tZSh0eXBlID0+IG5ldyBSZWdFeHAodHlwZSkudGVzdChmaWxlVHlwZSkpO1xyXG7CoCDCoCB9XHJcblxyXG7CoCDCoCBmdW5jdGlvbiB2YWxpZGF0ZUZpbGVTaXplICh7dXBsb2FkZWRGaWxlLCBtYXhTaXplfSkge1xyXG7CoCDCoCDCoCDCoCBpZighdXBsb2FkZWRGaWxlICYmICFtYXhTaXplKSByZXR1cm4gZmFsc2U7XHJcbsKgIMKgIMKgIMKgIGNvbnN0IHVwbG9hZGVkU2l6ZSA9IHVwbG9hZGVkRmlsZS5zaXplIC8gMTAyNCAvIDEwMjQ7IC8vIENvbnZlcnQgdG8gTUJcclxuwqAgwqAgwqAgwqAgcmV0dXJuIHVwbG9hZGVkU2l6ZSA8IChtYXhTaXplLmNbMF0gKyAwLjEpOyAvLyAwLjEgTUIgZXh0cmEgdG9sZXJhbmNlXHJcbsKgIMKgIH1cclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBXaGF0IGRvZXMgdGhpcyBKYXZhU2NyaXB0IEFjdGlvbiBkbz9cclxuICogXHJcbiAqIFRoaXMgaXMgYSBjdXN0b20gYnVpbGQgSmF2YVNjcmlwdCBBY3Rpb24gdGhhdCB0cmlnZ2VycyB0aGUgZmlsZSB1cGxvYWQgZGlhbG9nIGJveCB0byBvcGVuIGluIHlvdXIgaW50ZXJuZXQgYnJvd3Nlci4gXHJcbiAqIFxyXG4gKiBEZXBlbmRlbmN5IE5vdGU6IFxyXG4gKiBUaGlzIEphdmFTY3JpcHQgYWN0aW9uIHNob3VsZCBiZSB1c2VkIHdpdGggdGhlIEphdmFTY3JpcHQgQWN0aW9uIGNhbGxlZCAnSlNfUmV2b2tlVXBsb2FkZWRGaWxlRnJvbU1lbW9yeScgc28gdGhhdCB0aGUgaW1hZ2UgdXBsb2FkZWQgaXMgcmVtb3ZlZCBmcm9tIGxvY2FsIG1lbW9yeSA6KVxyXG4gKiBcclxuICogRXhwbGFuYXRpb24gb2YgdGhpcyBKYXZhU2NyaXB0IEFjdGlvbiAmIE1lbW9yeSBtYW5hZ2VtZW50LlxyXG4gKiBcclxuICogV2UgdXNlIGNyZWF0ZU9iamVjdFVSTCgpIHRvIHVwbG9hZCBhbmQgc3RvcmUgZmlsZXMgaW4gbG9jYWwgbWVtb3J5LiBXZSBjYW4gYWNjZXNzIGFuZCBjb3N1bWUgdGhpcyBpbiBtZW1vcnkgaW1hZ2UgcmVzb3VyY2UgdmlhIHRoZSBVUkwgcGF0aCB0aGF0IGlzIHJldHVybmVkIGZyb20gdGhlIGNyZWF0ZU9iamVjdFVSTCgpIG1ldGhvZC4gXHJcbiAqIFxyXG4gKiBIb3dldmVyLCBlYWNoIHRpbWUgeW91IGNhbGwgY3JlYXRlT2JqZWN0VVJMKCksIGEgbmV3IG9iamVjdCBpcyBjcmVhdGVkIGluIG1lbW9yeSwgZXZlbiBpZiB5b3UndmUgYWxyZWFkeSBjcmVhdGVkIG9uZSBmb3IgdGhlIHNhbWUgb2JqZWN0LiBcclxuICogU28gZWFjaCBvZiB0aGVzZSBtdXN0IGJlIHJlbGVhc2VkIGJ5IGNhbGxpbmcgdGhlIEpTIEFjdGlvbiBjYWxsZWQgJ0pTX1Jldm9rZVVwbG9hZGVkRmlsZUZyb21NZW1vcnknIHdoZW4geW91IG5vIGxvbmdlciBuZWVkIHRoZW0uXHJcbiAqIFxyXG4gKiBCcm93c2VycyB3aWxsIHJlbGVhc2Ugb2JqZWN0IFVSTHMgYXV0b21hdGljYWxseSB3aGVuIHRoZSBkb2N1bWVudCBpcyB1bmxvYWRlZDsgaG93ZXZlciwgZm9yIG9wdGltYWwgcGVyZm9ybWFuY2UgYW5kIG1lbW9yeSB1c2FnZSwgaWYgdGhlcmUgYXJlIHNhZmUgdGltZXMgd2hlbiB5b3UgY2FuIGV4cGxpY2l0bHkgdW5sb2FkIHRoZW0sIHlvdSBzaG91bGQgZG8gc28gd2l0aCB0aGUgSmF2YVNjcmlwdEFjdGlvbiBjYWxsZWQgJ0pTX1Jldm9rZVVwbG9hZGVkRmlsZUZyb21NZW1vcnknLlxyXG4gKiBAcGFyYW0ge3N0cmluZ30gdXNlckRlZmluZWRfbWltZVR5cGVzXHJcbiAqIEBwYXJhbSB7QmlnfSB1c2VyRGVmaW5lZF9maWxlVXBsb2FkU2l6ZVxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48c3RyaW5nPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19VcGxvYWRBbmRDb252ZXJ0VG9GaWxlQmxvYlVSTCh1c2VyRGVmaW5lZF9taW1lVHlwZXMsIHVzZXJEZWZpbmVkX2ZpbGVVcGxvYWRTaXplKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcbsKgIMKgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XHJcbsKgIMKgIMKgIMKgIHRyeSB7XHJcbsKgIMKgIMKgIMKgIMKgIMKgIC8vIENyZWF0ZSBhbmQgYXBwZW5kIHRoZSBIVE1MIGlucHV0IGVsZW1lbnQgdG8gdGhlIGJvZHlcclxuwqAgwqAgwqAgwqAgwqAgwqAgY29uc3QgZmlsZUlucHV0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudChcImlucHV0XCIpO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCBmaWxlSW5wdXQuc3R5bGUucG9zaXRpb24gPSBcImFic29sdXRlXCI7XHJcbsKgIMKgIMKgIMKgIMKgIMKgIGZpbGVJbnB1dC5zdHlsZS5sZWZ0ID0gXCItOTk5OXB4XCI7XHJcbsKgIMKgIMKgIMKgIMKgIMKgIGZpbGVJbnB1dC5uYW1lID0gXCJmaWxldXBsb2FkXCI7XHJcbsKgIMKgIMKgIMKgIMKgIMKgIGZpbGVJbnB1dC5pZCA9IFwiZmlsZXVwbG9hZFwiO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCBmaWxlSW5wdXQudHlwZSA9IFwiZmlsZVwiO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCBpZih1c2VyRGVmaW5lZF9taW1lVHlwZXMpe1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCBmaWxlSW5wdXQuYWNjZXB0ID0gdXNlckRlZmluZWRfbWltZVR5cGVzO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCB9XHJcbsKgIMKgIMKgIMKgIMKgIMKgIGZpbGVJbnB1dC5tdWx0aXBsZSA9IGZhbHNlO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCBmaWxlSW5wdXQub25jaGFuZ2UgPSBoYW5kbGVGaWxlVXBsb2FkO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGZpbGVJbnB1dCk7XHJcbiAgICAgICAgICAgIGZpbGVJbnB1dC5hZGRFdmVudExpc3RlbmVyKFwiY2FuY2VsXCIsICgpID0+IHJlc29sdmUoXCJ1cGxvYWRDYW5jZWxsZWRcIikpO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCBmaWxlSW5wdXQuY2xpY2soKTtcclxuXHJcbsKgIMKgIMKgIMKgIMKgIMKgIC8vIEEgZnVuY3Rpb24gdXNlZCB0byB2YWxpZGF0ZSAmIHN0b3JlIHRoZSB1cGxvYWRlZCBmaWxlIHRvIGxvY2FsIG1lbW9yeS5cclxuwqAgwqAgwqAgwqAgwqAgwqAgZnVuY3Rpb24gaGFuZGxlRmlsZVVwbG9hZChldmVudCkge1xyXG4gICAgICAgICAgICAgICAgaXNVcGxvYWRpbmcgPSB0cnVlO1xyXG4gIFxyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCBjb25zdCBuZXdGaWxlID0gZXZlbnQudGFyZ2V0LmZpbGVzWzBdO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCBjb25zdCBwcm9ncmVzc0lkID0gbXgudWkuc2hvd1Byb2dyZXNzKG51bGwsIHRydWUpO1xyXG5cclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgLy8gQ2hlY2sgaWYgdGhlIHVwbG9hZGVkIGZpbGUgdHlwZSBtYXRjaGVzIHRoZSB1c2VyIGRlZmluZWQgYWNjZXB0ZWQgdHlwZXMuXHJcbsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIGlmICghdmFsaWRhdGVGaWxlVHlwZXMoe2FjY2VwdGVkVHlwZXM6IGZpbGVJbnB1dC5hY2NlcHQsIGZpbGVUeXBlOiBuZXdGaWxlLnR5cGV9KSkge1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCByZW1vdmVEb21FbGVtZW50cyh7ZmlsZUlucHV0LCBwcm9ncmVzc0lkfSk7XHJcbsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIHJlc29sdmUoXCJmaWxlVHlwZU5vdEFjY2VwdGVkXCIpO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCByZXR1cm47XHJcbsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIH1cclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgLy8gQ2hlY2sgaWYgdGhlIHVwbG9hZGVkIGZpbGUgbWF0Y2hlcyB0aGUgdXNlciBkZWZpbmVkIHVwbG9hZCBzaXplLlxyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCBpZiAoIXZhbGlkYXRlRmlsZVNpemUoe3VwbG9hZGVkRmlsZTogbmV3RmlsZSwgbWF4U2l6ZTogdXNlckRlZmluZWRfZmlsZVVwbG9hZFNpemV9KSkgeyBcclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgcmVtb3ZlRG9tRWxlbWVudHMoe2ZpbGVJbnB1dCwgcHJvZ3Jlc3NJZH0pO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCByZXNvbHZlKFwiZmlsZVNpemVOb3RBY2NlcHRlZFwiKTtcclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgcmV0dXJuO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCB9XHJcbsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIC8vIFN0b3JlIGZpbGUgbG9jYWxseSBvbiB1c2VycyBkZXZpY2UgYW5kIHJldHVybiBwYXRoIHRvIHJlc291cmNlLlxyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCBzdG9yZUZpbGVBbmRHZXRSZXNvdXJjZVVybChuZXdGaWxlKS50aGVuKChmaWxlQmxvYlVSTCkgPT4ge1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCBpZihmaWxlQmxvYlVSTCAmJiB0eXBlb2YgZmlsZUJsb2JVUkwgPT09IFwic3RyaW5nXCIpIHtcclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgcmVtb3ZlRG9tRWxlbWVudHMoe2ZpbGVJbnB1dCwgcHJvZ3Jlc3NJZH0pO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCByZXNvbHZlKGZpbGVCbG9iVVJMKTtcclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgfSBlbHNlIHtcclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgcmVtb3ZlRG9tRWxlbWVudHMoe2ZpbGVJbnB1dCwgcHJvZ3Jlc3NJZH0pO1xyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCByZXNvbHZlKFwiZmlsZU5vdENvbnZlcnRlZFwiKTtcclxuwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgfVxyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCB9KVxyXG7CoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCByZXR1cm47XHJcbsKgIMKgIMKgIMKgIMKgIMKgIH07XHJcbsKgIMKgIMKgIMKgIH0gY2F0Y2ggKGVycm9yKSB7XHJcbsKgIMKgIMKgIMKgIMKgIMKgIHJlamVjdChlcnJvcik7XHJcbsKgIMKgIMKgIMKgIH1cclxuwqAgwqAgfSk7XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuaW1wb3J0IEFzeW5jU3RvcmFnZSBmcm9tICdAcmVhY3QtbmF0aXZlLWNvbW11bml0eS9hc3luYy1zdG9yYWdlJztcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBTdG9yZSBhIE1lbmRpeCBvYmplY3QgaW4gZGV2aWNlIHN0b3JhZ2UsIGlkZW50aWZpZWQgYnkgYSB1bmlxdWUga2V5LiBDYW4gYmUgYWNjZXNlZCBieSB0aGUgR2V0U3RhcmdlSXRlbU9iamVjdCBhY3Rpb24uIFBsZWFzZSBub3RlIHRoYXQgdXNlcnMgY2FuIGNsZWFyIHRoZSBkZXZpY2Ugc3RvcmFnZS5cclxuICogQHBhcmFtIHtzdHJpbmd9IGtleSAtIFRoaXMgZmllbGQgaXMgcmVxdWlyZWQuXHJcbiAqIEBwYXJhbSB7TXhPYmplY3R9IHZhbHVlIC0gVGhpcyBmaWVsZCBpcyByZXF1aXJlZC5cclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIFNldFN0b3JhZ2VJdGVtT2JqZWN0KGtleSwgdmFsdWUpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuICAgIGlmICgha2V5KSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIklucHV0IHBhcmFtZXRlciAnS2V5JyBpcyByZXF1aXJlZFwiKSk7XHJcbiAgICB9XHJcbiAgICBpZiAoIXZhbHVlKSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIklucHV0IHBhcmFtZXRlciAnVmFsdWUnIGlzIHJlcXVpcmVkXCIpKTtcclxuICAgIH1cclxuICAgIGNvbnN0IHNlcmlhbGl6ZWRPYmplY3QgPSBzZXJpYWxpemVNeE9iamVjdCh2YWx1ZSk7XHJcbiAgICByZXR1cm4gc2V0SXRlbShrZXksIEpTT04uc3RyaW5naWZ5KHNlcmlhbGl6ZWRPYmplY3QpKTtcclxuICAgIGZ1bmN0aW9uIHNldEl0ZW0oa2V5LCB2YWx1ZSkge1xyXG4gICAgICAgIGlmIChuYXZpZ2F0b3IgJiYgbmF2aWdhdG9yLnByb2R1Y3QgPT09IFwiUmVhY3ROYXRpdmVcIikge1xyXG4gICAgICAgICAgICByZXR1cm4gQXN5bmNTdG9yYWdlLnNldEl0ZW0oa2V5LCB2YWx1ZSk7XHJcbiAgICAgICAgfVxyXG4gICAgICAgIGlmICh3aW5kb3cpIHtcclxuICAgICAgICAgICAgd2luZG93LmxvY2FsU3RvcmFnZS5zZXRJdGVtKGtleSwgdmFsdWUpO1xyXG4gICAgICAgICAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKCk7XHJcbiAgICAgICAgfVxyXG4gICAgICAgIHJldHVybiBQcm9taXNlLnJlamVjdChuZXcgRXJyb3IoXCJObyBzdG9yYWdlIEFQSSBhdmFpbGFibGVcIikpO1xyXG4gICAgfVxyXG4gICAgZnVuY3Rpb24gc2VyaWFsaXplTXhPYmplY3Qob2JqZWN0KSB7XHJcbiAgICAgICAgcmV0dXJuIG9iamVjdC5nZXRBdHRyaWJ1dGVzKCkucmVkdWNlKChhY2N1bXVsYXRvciwgYXR0cmlidXRlTmFtZSkgPT4ge1xyXG4gICAgICAgICAgICBhY2N1bXVsYXRvclthdHRyaWJ1dGVOYW1lXSA9IG9iamVjdC5nZXQoYXR0cmlidXRlTmFtZSk7XHJcbiAgICAgICAgICAgIHJldHVybiBhY2N1bXVsYXRvcjtcclxuICAgICAgICB9LCB7IGd1aWQ6IG9iamVjdC5nZXRHdWlkKCkgfSk7XHJcbiAgICB9XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIm1vZHVsZS5leHBvcnRzID0gX19XRUJQQUNLX0VYVEVSTkFMX01PRFVMRV9iaWdfanNfXzsiLCIvKiBlbXB0eSAqLyIsIi8vIFRoZSBtb2R1bGUgY2FjaGVcbnZhciBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX18gPSB7fTtcblxuLy8gVGhlIHJlcXVpcmUgZnVuY3Rpb25cbmZ1bmN0aW9uIF9fd2VicGFja19yZXF1aXJlX18obW9kdWxlSWQpIHtcblx0Ly8gQ2hlY2sgaWYgbW9kdWxlIGlzIGluIGNhY2hlXG5cdHZhciBjYWNoZWRNb2R1bGUgPSBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX19bbW9kdWxlSWRdO1xuXHRpZiAoY2FjaGVkTW9kdWxlICE9PSB1bmRlZmluZWQpIHtcblx0XHRyZXR1cm4gY2FjaGVkTW9kdWxlLmV4cG9ydHM7XG5cdH1cblx0Ly8gQ3JlYXRlIGEgbmV3IG1vZHVsZSAoYW5kIHB1dCBpdCBpbnRvIHRoZSBjYWNoZSlcblx0dmFyIG1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF0gPSB7XG5cdFx0Ly8gbm8gbW9kdWxlLmlkIG5lZWRlZFxuXHRcdC8vIG5vIG1vZHVsZS5sb2FkZWQgbmVlZGVkXG5cdFx0ZXhwb3J0czoge31cblx0fTtcblxuXHQvLyBFeGVjdXRlIHRoZSBtb2R1bGUgZnVuY3Rpb25cblx0X193ZWJwYWNrX21vZHVsZXNfX1ttb2R1bGVJZF0obW9kdWxlLCBtb2R1bGUuZXhwb3J0cywgX193ZWJwYWNrX3JlcXVpcmVfXyk7XG5cblx0Ly8gUmV0dXJuIHRoZSBleHBvcnRzIG9mIHRoZSBtb2R1bGVcblx0cmV0dXJuIG1vZHVsZS5leHBvcnRzO1xufVxuXG4iLCIvLyBnZXREZWZhdWx0RXhwb3J0IGZ1bmN0aW9uIGZvciBjb21wYXRpYmlsaXR5IHdpdGggbm9uLWhhcm1vbnkgbW9kdWxlc1xuX193ZWJwYWNrX3JlcXVpcmVfXy5uID0gKG1vZHVsZSkgPT4ge1xuXHR2YXIgZ2V0dGVyID0gbW9kdWxlICYmIG1vZHVsZS5fX2VzTW9kdWxlID9cblx0XHQoKSA9PiAobW9kdWxlWydkZWZhdWx0J10pIDpcblx0XHQoKSA9PiAobW9kdWxlKTtcblx0X193ZWJwYWNrX3JlcXVpcmVfXy5kKGdldHRlciwgeyBhOiBnZXR0ZXIgfSk7XG5cdHJldHVybiBnZXR0ZXI7XG59OyIsIi8vIGRlZmluZSBnZXR0ZXIgZnVuY3Rpb25zIGZvciBoYXJtb255IGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uZCA9IChleHBvcnRzLCBkZWZpbml0aW9uKSA9PiB7XG5cdGZvcih2YXIga2V5IGluIGRlZmluaXRpb24pIHtcblx0XHRpZihfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZGVmaW5pdGlvbiwga2V5KSAmJiAhX193ZWJwYWNrX3JlcXVpcmVfXy5vKGV4cG9ydHMsIGtleSkpIHtcblx0XHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBrZXksIHsgZW51bWVyYWJsZTogdHJ1ZSwgZ2V0OiBkZWZpbml0aW9uW2tleV0gfSk7XG5cdFx0fVxuXHR9XG59OyIsIl9fd2VicGFja19yZXF1aXJlX18ubyA9IChvYmosIHByb3ApID0+IChPYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LmNhbGwob2JqLCBwcm9wKSkiLCIvLyBkZWZpbmUgX19lc01vZHVsZSBvbiBleHBvcnRzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLnIgPSAoZXhwb3J0cykgPT4ge1xuXHRpZih0eXBlb2YgU3ltYm9sICE9PSAndW5kZWZpbmVkJyAmJiBTeW1ib2wudG9TdHJpbmdUYWcpIHtcblx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgU3ltYm9sLnRvU3RyaW5nVGFnLCB7IHZhbHVlOiAnTW9kdWxlJyB9KTtcblx0fVxuXHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgJ19fZXNNb2R1bGUnLCB7IHZhbHVlOiB0cnVlIH0pO1xufTsiLCJleHBvcnQgY29uc3QgRmVlZGJhY2tNb2R1bGUkSlNfUG9wdWxhdGVGZWVkYmFja01ldGFkYXRhID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL0pTX1BvcHVsYXRlRmVlZGJhY2tNZXRhZGF0YVwiKSkuSlNfUG9wdWxhdGVGZWVkYmFja01ldGFkYXRhO1xuZXhwb3J0IGNvbnN0IEZlZWRiYWNrTW9kdWxlJFNldFN0b3JhZ2VJdGVtT2JqZWN0ID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL1NldFN0b3JhZ2VJdGVtT2JqZWN0XCIpKS5TZXRTdG9yYWdlSXRlbU9iamVjdDtcbmV4cG9ydCBjb25zdCBGZWVkYmFja01vZHVsZSRKU19Ub2dnbGVGZWVkYmFja1NjcmVlbnNob3RXaWRnZXQgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvemZfa2FyYXltZWgvUHJvamVjdHMvbmF0aXZlQ2FyZFdhbGxldC90ZXN0UHJvamVjdC9qYXZhc2NyaXB0c291cmNlL2ZlZWRiYWNrbW9kdWxlL2FjdGlvbnMvSlNfVG9nZ2xlRmVlZGJhY2tTY3JlZW5zaG90V2lkZ2V0XCIpKS5KU19Ub2dnbGVGZWVkYmFja1NjcmVlbnNob3RXaWRnZXQ7XG5leHBvcnQgY29uc3QgRmVlZGJhY2tNb2R1bGUkSlNfVXBsb2FkQW5kQ29udmVydFRvRmlsZUJsb2JVUkwgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvemZfa2FyYXltZWgvUHJvamVjdHMvbmF0aXZlQ2FyZFdhbGxldC90ZXN0UHJvamVjdC9qYXZhc2NyaXB0c291cmNlL2ZlZWRiYWNrbW9kdWxlL2FjdGlvbnMvSlNfVXBsb2FkQW5kQ29udmVydFRvRmlsZUJsb2JVUkxcIikpLkpTX1VwbG9hZEFuZENvbnZlcnRUb0ZpbGVCbG9iVVJMO1xuZXhwb3J0IGNvbnN0IEZlZWRiYWNrTW9kdWxlJEpTX1RvZ2dsZUZlZWRiYWNrQW5ub3RhdGVXaWRnZXQgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvemZfa2FyYXltZWgvUHJvamVjdHMvbmF0aXZlQ2FyZFdhbGxldC90ZXN0UHJvamVjdC9qYXZhc2NyaXB0c291cmNlL2ZlZWRiYWNrbW9kdWxlL2FjdGlvbnMvSlNfVG9nZ2xlRmVlZGJhY2tBbm5vdGF0ZVdpZGdldFwiKSkuSlNfVG9nZ2xlRmVlZGJhY2tBbm5vdGF0ZVdpZGdldDtcbmV4cG9ydCBjb25zdCBGZWVkYmFja01vZHVsZSRKU19SZXZva2VVcGxvYWRlZEZpbGVGcm9tTWVtb3J5ID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL3pmX2thcmF5bWVoL1Byb2plY3RzL25hdGl2ZUNhcmRXYWxsZXQvdGVzdFByb2plY3QvamF2YXNjcmlwdHNvdXJjZS9mZWVkYmFja21vZHVsZS9hY3Rpb25zL0pTX1Jldm9rZVVwbG9hZGVkRmlsZUZyb21NZW1vcnlcIikpLkpTX1Jldm9rZVVwbG9hZGVkRmlsZUZyb21NZW1vcnk7XG5leHBvcnQgY29uc3QgRmVlZGJhY2tNb2R1bGUkR2V0U3RvcmFnZUl0ZW1PYmplY3QgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvemZfa2FyYXltZWgvUHJvamVjdHMvbmF0aXZlQ2FyZFdhbGxldC90ZXN0UHJvamVjdC9qYXZhc2NyaXB0c291cmNlL2ZlZWRiYWNrbW9kdWxlL2FjdGlvbnMvR2V0U3RvcmFnZUl0ZW1PYmplY3RcIikpLkdldFN0b3JhZ2VJdGVtT2JqZWN0O1xuIl0sIm5hbWVzIjpbIkJpZyIsIkFzeW5jU3RvcmFnZSIsIkdldFN0b3JhZ2VJdGVtT2JqZWN0Iiwia2V5IiwiZW50aXR5IiwiUHJvbWlzZSIsInJlamVjdCIsIkVycm9yIiwiZ2V0SXRlbSIsInRoZW4iLCJyZXN1bHQiLCJ2YWx1ZSIsIkpTT04iLCJwYXJzZSIsImdldE9yQ3JlYXRlTXhPYmplY3QiLCJuZXdPYmplY3QiLCJuZXdWYWx1ZSIsInNlcmlhbGl6ZU14T2JqZWN0Iiwic2V0SXRlbSIsInN0cmluZ2lmeSIsIm5hdmlnYXRvciIsInByb2R1Y3QiLCJ3aW5kb3ciLCJsb2NhbFN0b3JhZ2UiLCJyZXNvbHZlIiwiZ2V0TXhPYmplY3QiLCJndWlkIiwiZXhpc3RpbmdPYmplY3QiLCJjcmVhdGVNeE9iamVjdCIsIm14IiwiZGF0YSIsImdldCIsImNhbGxiYWNrIiwibXhPYmplY3QiLCJlcnJvciIsImNyZWF0ZSIsIk9iamVjdCIsImtleXMiLCJmaWx0ZXIiLCJhdHRyaWJ1dGUiLCJmb3JFYWNoIiwiYXR0cmlidXRlTmFtZSIsImF0dHJpYnV0ZVZhbHVlIiwic2V0Iiwib2JqZWN0IiwiZ2V0QXR0cmlidXRlcyIsInJlZHVjZSIsImFjY3VtdWxhdG9yIiwiZ2V0R3VpZCIsImhhbmRsZVVzZXJSb2xlcyIsInVuZGVmaW5lZCIsInNlc3Npb24iLCJnZXRVc2VyUm9sZU5hbWVzIiwiY29uc29sZSIsImhhbmRsZVBhZ2VQYXRoIiwibWVuZGl4VmVyc2lvbiIsInZlcnNpb24iLCJtZW5kaXhNYWpvclZlcnNpb24iLCJzcGxpdCIsInVpIiwiZ2V0Q29udGVudEZvcm0iLCJwYXRoIiwidG9TdHJpbmciLCJKU19Qb3B1bGF0ZUZlZWRiYWNrTWV0YWRhdGEiLCJmZWVkYmFjayIsInVzZXJSb2xlcyIsInBhZ2VQYXRoIiwibG9jYXRpb24iLCJocmVmIiwidXNlckFnZW50Iiwic2NyZWVuIiwid2lkdGgiLCJoZWlnaHQiLCJKU19SZXZva2VVcGxvYWRlZEZpbGVGcm9tTWVtb3J5IiwiZmlsZUJsb2JVUkwiLCJVUkwiLCJyZXZva2VPYmplY3RVUkwiLCJtZXNzYWdlQWN0aW9uX3RvZ2dsZUFubm90YXRlTW9kZSIsIm1lc3NhZ2VBY3Rpb25faXNCYXNlNjQiLCJtZXNzYWdlQWN0aW9uX2FjdGlvbkNhbmNlbGxlZCIsInBhcnNlSlNPTiIsImV2ZW50IiwiSlNfVG9nZ2xlRmVlZGJhY2tBbm5vdGF0ZVdpZGdldCIsIm1lc3NhZ2VPYmplY3QiLCJwb3N0TWVzc2FnZSIsIm9yaWdpbiIsImhhbmRsZUV2ZW50IiwicGFyc2VkRGF0YSIsIm1lc3NhZ2VBY3Rpb25UeXBlIiwicmVtb3ZlRXZlbnRMaXN0ZW5lciIsIm1lc3NhZ2VEYXRhIiwiYWRkRXZlbnRMaXN0ZW5lciIsInBhcnNlSnNvbiIsIkpTX1RvZ2dsZUZlZWRiYWNrU2NyZWVuc2hvdFdpZGdldCIsImlzVXBsb2FkaW5nIiwic3RvcmVGaWxlQW5kR2V0UmVzb3VyY2VVcmwiLCJmaWxlIiwiY3JlYXRlT2JqZWN0VVJMIiwicmVtb3ZlRG9tRWxlbWVudHMiLCJfcmVmIiwiZmlsZUlucHV0IiwicHJvZ3Jlc3NJZCIsImhpZGVQcm9ncmVzcyIsImRvY3VtZW50IiwiYm9keSIsInJlbW92ZUNoaWxkIiwidmFsaWRhdGVGaWxlVHlwZXMiLCJfcmVmMiIsImFjY2VwdGVkVHlwZXMiLCJmaWxlVHlwZSIsImFjY2VwdGVkIiwic29tZSIsInR5cGUiLCJSZWdFeHAiLCJ0ZXN0IiwidmFsaWRhdGVGaWxlU2l6ZSIsIl9yZWYzIiwidXBsb2FkZWRGaWxlIiwibWF4U2l6ZSIsInVwbG9hZGVkU2l6ZSIsInNpemUiLCJjIiwiSlNfVXBsb2FkQW5kQ29udmVydFRvRmlsZUJsb2JVUkwiLCJ1c2VyRGVmaW5lZF9taW1lVHlwZXMiLCJ1c2VyRGVmaW5lZF9maWxlVXBsb2FkU2l6ZSIsImNyZWF0ZUVsZW1lbnQiLCJzdHlsZSIsInBvc2l0aW9uIiwibGVmdCIsIm5hbWUiLCJpZCIsImFjY2VwdCIsIm11bHRpcGxlIiwib25jaGFuZ2UiLCJoYW5kbGVGaWxlVXBsb2FkIiwiYXBwZW5kQ2hpbGQiLCJjbGljayIsIm5ld0ZpbGUiLCJ0YXJnZXQiLCJmaWxlcyIsInNob3dQcm9ncmVzcyIsIlNldFN0b3JhZ2VJdGVtT2JqZWN0Iiwic2VyaWFsaXplZE9iamVjdCIsIkZlZWRiYWNrTW9kdWxlJEpTX1BvcHVsYXRlRmVlZGJhY2tNZXRhZGF0YSIsIkZlZWRiYWNrTW9kdWxlJFNldFN0b3JhZ2VJdGVtT2JqZWN0IiwiRmVlZGJhY2tNb2R1bGUkSlNfVG9nZ2xlRmVlZGJhY2tTY3JlZW5zaG90V2lkZ2V0IiwiRmVlZGJhY2tNb2R1bGUkSlNfVXBsb2FkQW5kQ29udmVydFRvRmlsZUJsb2JVUkwiLCJGZWVkYmFja01vZHVsZSRKU19Ub2dnbGVGZWVkYmFja0Fubm90YXRlV2lkZ2V0IiwiRmVlZGJhY2tNb2R1bGUkSlNfUmV2b2tlVXBsb2FkZWRGaWxlRnJvbU1lbW9yeSIsIkZlZWRiYWNrTW9kdWxlJEdldFN0b3JhZ2VJdGVtT2JqZWN0Il0sInNvdXJjZVJvb3QiOiIifQ==